Object.assign(window.SCHOOLS, {
  "XBA5043/S01003": {"nama":"KAFA KG. MALIYU BANGGI","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5035/S01016": {"nama":"KAFA KG. DAMARAN BANGGI","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5022/S01005": {"nama":"KAFA KG. BATU PUTIH BANGGI","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5024/S01007": {"nama":"KAFA KG. KOBONG LAUT BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5025/S01008": {"nama":"KAFA KG. LOK TUHOG BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5027/S01009": {"nama":"KAFA AGROPOLITAN BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5028/S01010": {"nama":"KAFA KG. BATU LAYAR BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5042/S01019": {"nama":"KAFA KG. LUMAIS BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5031/S01012": {"nama":"KAFA KG. LIMBUAK LAUT BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5032/S01013": {"nama":"KAFA KG. TIMBANG DAYANG BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5034/S01015": {"nama":"KAFA KG. LAKSIAN BANGGI","daerah":"BANGGI","negeri":"SABAH"},
  "XYT5037/S01017": {"nama":"KAFA KG. TANJUNG MANAWALI BANGGI ","daerah":"BANGGI","negeri":"SABAH"},
  "SIMPANAN-BANGGI": {"nama":"KAFA KG. BATU PUTIH BANGGI","daerah":"BANGGI","negeri":"SABAH"},
    "XYP6001 / S02001": {"nama":"KAFA SAN PEKAN BEAUFORT","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6003 / S02002": {"nama":"KAFA SAN KG.LUBAK BEAUFORT","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6005 / S02003": {"nama":"KAFA SAN KG. TAKULI","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6006 / S02004": {"nama":"KAFA SAN KG.KABIDANG","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6011 / S02005": {"nama":"KAFA SAN KG.KUKUT","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6012 / S02006": {"nama":"KAFA SAN KG. KLIAS KECIL","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6014 / S02007": {"nama":"KAFA SAN KG BINGKUL","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6018 / S02008": {"nama":"KAFA SAN KG.KOTA KLIAS","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYP6206 / S02009": {"nama":"KAFA SAN KG.RANCANGAN KLIAS","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYQ6001/ S02011": {"nama":"SEKOLAH AGAMA RAKYAT KG KLIAS BARU","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYQ6003 / S02012": {"nama":"SEKOLAH AGAMA RAKYAT KAFA KG. KABULU","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYT6002 / S02014": {"nama":"KAFA KG SELAGON","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYT6014 / S02015": {"nama":"KAFA SAN KG. LABA","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYT6015  / S02016": {"nama":"BANGUNAN KHAS KAFA KG NUKAHAN","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYT6016  / S02017": {"nama":"KAFA KG. LUMAT","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "XYT6017 / S02018": {"nama":"BANGUNAN KHAS KAFA KG MUHIBBAH BARU","daerah":"BEAUFORT 1","negeri":"SABAH"},
  "SIMPANAN-BEAUFORT-1": {"nama":"PEJABAT PERHUBUNGAN KAFA DAERAH BEAUFORT, D/A PEJABAT DAERAH BEAUFORT","daerah":"BEAUFORT 1","negeri":"SABAH"},
    "XBA6013 / S03001": {"nama":"KAFA SK KABAJANG","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XBA6019  / S03002": {"nama":"KAFA SK KEPAWA","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XBA6020 / S03003": {"nama":"KAFA SK BINTUKA","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XBA6037 / S03004": {"nama":"KAFA SK MARABA","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XBA6067 / S03005": {"nama":"KAFA KG JABANG","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYP6007 / S03006": {"nama":"KAFA SAN KG GADONG","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYP6009 / S03007": {"nama":"KAFA SAN KG LUMADAN","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYP6013 / S03008": {"nama":"KAFA SAN KG BATANDOK","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYQ6004 / S03009": {"nama":"KAFA SAR LINGKUNGAN","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYQ6005 / S03010": {"nama":"KAFA PADAS DAMIT","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYQ6007 / S03011": {"nama":"KAFA SAR BANGKALALAK","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYQ6008 / S03012": {"nama":"KAFA SAR KAMPUNG LUBOK","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYQ6009 / S03013": {"nama":"KAFA SAR LUPAK","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6003 / S03014": {"nama":"KAFA SURAU KILANG SAWIT LUMADAN","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6004 / S03015": {"nama":"KAFA LAGO","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6005 / S03016": {"nama":"KAFA SUASA","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6006 / S03017": {"nama":"KAFA KUALA BALIK","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6018 / S03018": {"nama":"KAFA AL-HIDAYAH , KAMPUNG LUAGAN","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "XYT6019 / S03019": {"nama":"KAFA MASJID GARAMA","daerah":"BEAUFORT 2","negeri":"SABAH"},
  "SIMPANAN-BEAUFORT-2": {"nama":"SIMPANAN DAERAH","daerah":"BEAUFORT 2","negeri":"SABAH"},
    "XYP2101/S04001": {"nama":"SAN PEKAN BELURAN","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2101/S04004": {"nama":"KAFA NUR S'ZAMI KG KERAMAT","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2105/S04005": {"nama":"KAFA SAR KG KENIOGAN","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2106/S04006": {"nama":"KAFA AL-ADIB TERUSAN SUGUT","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2107/S04007": {"nama":"KAFA AL-FALAH ULU MUANAD","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2109/S04008": {"nama":"KAFA NUR-ILHAM","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2112/S04009": {"nama":"KAFA NUR ISLAM","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2114/S04010": {"nama":"KAFA IBNU KATHIR","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2117/S04011": {"nama":"KAFA MASJID BABUS SALAM","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2121/S04012": {"nama":"KAFA AN-NUHA","daerah":"BELURAN","negeri":"SABAH"},
  "SYT2123/S04013": {"nama":"KAFA NURUL IMAN AT-TAQWA","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2124/S04014": {"nama":"KAFA JAMIUR RAHMAN BELURAN","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2158/S04016": {"nama":"KAFA SRI MEMANTI BELURAN","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2165/S04017": {"nama":"KAFA AL-SYUKRI KG AIR BELURAN","daerah":"BELURAN","negeri":"SABAH"},
  "XYT2166/S04018": {"nama":"KAFA SURAU AN-NUR IPD BELURAN","daerah":"BELURAN","negeri":"SABAH"},
  "SIMPANAN-BELURAN": {"nama":"SIMPANAN DAERAH","daerah":"BELURAN","negeri":"SABAH"},
    "XBA1015/S05001": {"nama":"KAFA SK. BINGKOR","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1016/S05002": {"nama":"KAFA SK. BUNDU APIN-APIN","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1017/S05003": {"nama":"KAFA SK. APIN-APIN","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1018/S05004": {"nama":"KAFA SK. KAMPUNG BARU","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1020/S05005": {"nama":"KAFA SK. BANJAR","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1022/S05006": {"nama":"KAFA SK. JAYA BARU","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1024/S05007": {"nama":"KAFA SK. SENAGANG","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1025/S05008": {"nama":"KAFA SK. PASIR PUTIH","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1026/S05009": {"nama":"KAFA SK. MERAMPONG","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1027/S05010": {"nama":"KAFA SK. KARAMATOI","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1028/S05011": {"nama":"KAFA SK. TULID","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1030/S05012": {"nama":"KAFA SK. MALAING","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1031/S05013": {"nama":"KAFA SK. SODOMON","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1032/S05014": {"nama":"KAFA SK. LIAWAN","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1033/S05015": {"nama":"KAFA SK. LUAGAN","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1034/S05016": {"nama":"KAFA SK. KENINGAU II","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1035/S05017": {"nama":"KAFA SK. PEKAN KENINGAU","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1036/S05018": {"nama":"KAFA SK. JALAN APIN-APIN","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1037/S05019": {"nama":"KAFA SK. BARIAWA ULU","daerah":"KENINGAU 1","negeri":"SABAH"},
  "XBA1038/S05020": {"nama":"KAFA SK. BARIAWA TENGAH","daerah":"KENINGAU 1","negeri":"SABAH"},
  "SIMPANAN-KENINGAU-1": {"nama":"SIMPANAN DAERAH","daerah":"KENINGAU 1","negeri":"SABAH"},
    "XBA1003 / S06001": {"nama":"KAFA SK BANJAR","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XBA1019 / S06002": {"nama":"KAFA SK KAMPUNG KENINGAU","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XBA1076 / S06003": {"nama":"KAFA SK PEKAN KENINGAU 2","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XYQ1004 / S06006": {"nama":"KAFA SAR BARIAWA ULU","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XYT1000 / S06007": {"nama":"KAFA SURAU AN-NUR KG GAULAN","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XYT1002 / S06008": {"nama":"KAFA  KG LIMBAWAN","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XYT1003 / S06009": {"nama":"KAFA KG PANAGATAN LAUT","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XYT1007 / S06010": {"nama":"KAFA SURAU AL-AMIN BALAI BOMBA","daerah":"KENINGAU 2","negeri":"SABAH"},
  "XBA1018 / S06012": {"nama":"KAFA SK KAMPONG BIAH","daerah":"KENINGAU 2","negeri":"SABAH"},
  "SIMPANAN-KENINGAU-2": {"nama":"SIMPANAN DAERAH","daerah":"KENINGAU 2","negeri":"SABAH"},
    "XYT2201/ S07001": {"nama":"KAFA MASJID SUNGAI TAKALA KAMPUNG PARIS 1","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2203/S07003": {"nama":"KAFA SURAU KAMPUNG SRI MANIS KINABATANGAN","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2204/ S07004": {"nama":"KAFA KAMPUNG MANGGIS BUANG SAYANG KINABATANGAN","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2206/ S07006": {"nama":"KAFA KG GOMANTONG JAYA","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2208/ S07008": {"nama":"KAFA MASJID NURUL IMAN KG SUKAU","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2210/ S07009": {"nama":"KAFA TAMAN BUKIT PERMATA","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2212/ S07010": {"nama":"KAFA MADRASAH PADUAN KG NUSA JAYA","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2214/ S07011": {"nama":"KAFA KG BATU PUTIH","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2215/ S07012": {"nama":"KAFA MASJID AN-NURJANNAH KG PELANGI","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2216/ S07013": {"nama":"KAFA MADRASAH AR-RAHMAH KG WARISAN","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2219/ S07014": {"nama":"KAFA MASJID DAERAH KINABATANGAN","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2226/ S07019": {"nama":"KAFA MASJID AL-HILAL BATU 6","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2230/ S07022": {"nama":"KAFA MASJID AT-TAQWA KG USAHA JAYA BATU 3","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2235/ S07024": {"nama":"KAFA MASJID RAUDHATUL JANNAH KG BUANG SAYANG","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2236/ S07025": {"nama":"KAFA KG SANGAU","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2241/ S07026": {"nama":"KAFA MASJID AL-FALLAH KG RANTAU ABANG","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2243/ S07027": {"nama":"KAFA MASJID AL-FURQAN KG SINAR JAYA","daerah":"KINABATANGAN","negeri":"SABAH"},
  "XYT2250/ S07030": {"nama":"KAFA MADRASAH KG  KASIH SAYANG","daerah":"KINABATANGAN","negeri":"SABAH"},
  "SIMPANAN-KINABATANGAN": {"nama":"SIMPANAN DAERAH","daerah":"KINABATANGAN","negeri":"SABAH"},
    "XYQ5302 / S08003": {"nama":"KAFA SAR KG KULAMBAI","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5308 / S08016": {"nama":"KAFA AL-HIJRAH KG. KUALA ABAI","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5336 / S08022": {"nama":"(KB 1 ) KAFA BANGUNAN KHAS KG. BIRA-BIRAAN","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5304 / S08004": {"nama":"KAFA SAR LABUAN","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5309 / S08017": {"nama":"KAFA MASJID KG. GUNDING","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5310 / S08018": {"nama":"KAFA MASJID KG JAWI-JAWI","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5471 / S0823": {"nama":"KAFA KAMPUNG BATU ENAM","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5308 / S08005": {"nama":"KAFA SAR PERPADUAN","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5303 /S08011": {"nama":"KAFA BALAIRAYA KG. PANTAI EMAS","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5311 / S08007": {"nama":"KAFA SAR NUR TAQWA KAMPUNG RAMPAYAN LAUT KOTA BELUD","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYP5306 / S08002": {"nama":"KAFA SAN MERABAU","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5310 / S08006": {"nama":"KAFA SAR AL-HIKMAH","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT6067 / S08024": {"nama":"KAFA BALAIRAYA KG KAYU PUTIH","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5315 / S08008": {"nama":"KAFA SAR AS-SYAKIRIN","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYQ5316 / S08009": {"nama":"KAFA SAR DARUL BAKTI ","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5301 / S08010": {"nama":"KAFA BALAIRAYA KG LINAU","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "XYT5306 / S08014": {"nama":"KAFA BALAIRAYA KG SIASAI KUMPANG","daerah":"KOTA BELUD 1","negeri":"SABAH"},
  "SIMPANAN-KOTA-BELUD-1": {"nama":"SIMPANAN DAERAH","daerah":"KOTA BELUD 1","negeri":"SABAH"},
    "XBA5332/S09001": {"nama":"KAFA PULAU MANTANANI","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYQ5303/S09002": {"nama":"KAFA SAR KG SUANG PUNGGOR","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5339/S09007": {"nama":"KAFA BUAH PANDAI","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5351/S09018": {"nama":"KAFA KG. SONG-SONG","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYQ5313/S09003": {"nama":"SAR KAFA IBNU SINA KG PANGKALAN ABAI","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5341 /S09009": {"nama":"KAFA KG. LINGKODON","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5348/S09016": {"nama":"KAFA TAMAN NIKMAT KOTA BELUD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5349/S09017": {"nama":"KAFA KG. LENTIGI","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT6068/S09019": {"nama":"KAFA MASJID KG PAKA-PAKA","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYQ5318/S09004": {"nama":"SAR KAFA AT-TARBIYYAH PEKAN KOTA BELUD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYQ5319/S09005": {"nama":"KAFA SAR TEMPAUS KOTA BELUD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5343/S09011": {"nama":"KAFA MASJID KG LEBAK ENGAD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5340/S09008": {"nama":"KAFA KG KOTA BELUD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5346 /S09014": {"nama":"KAFA BANGUNAN KHAS KG. BARU-BARU","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT6061/S09020": {"nama":"KAFA KG LOK NUNUK","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5342/S09010": {"nama":"KAFA KG. AMBONG","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5347/S09015": {"nama":"KAFA SURAU KG PITURU DARAT","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "XYT5338/S09006": {"nama":"KAFA KAMPUNG LOBONG-LOBONG KOTA BELUD","daerah":"KOTA BELUD 2","negeri":"SABAH"},
  "SIMPANAN-KOTA-BELUD-2": {"nama":"SIMPANAN DAERAH","daerah":"KOTA BELUD 2","negeri":"SABAH"},
    "XYT5318/S10007": {"nama":"KAFA SURAU KG SARANG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5334/S10021": {"nama":"KAFA SURAU KG DUDAR","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5362/S10025": {"nama":"KAFA SURAU AN-NUR KG TIMBANG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT6069/S10026": {"nama":"KAFA SURAU KG TABURAN","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYQ5306/S10002": {"nama":"KAFA SAR RAMPAYAN ULU","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYQ5314/S10003": {"nama":"KAFA SAR TAMBULION","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5314/S10005": {"nama":"KAFA KG PIRASAN","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XBA5330/S10001": {"nama":"KAFA SURAU SK PIASAU","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5320/S10009": {"nama":"KAFA SURAU KG PIRASAN ULU","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5360/S10023": {"nama":"KAFA SURAU NUR HIKMAH KG TEMPASUK 2","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5337/S10022": {"nama":"KAFA IHSANIYYAH KG SIASAI TAMU","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT6062/S10024": {"nama":"KAFA SURAU KG TENGKURUS","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5321/S10010": {"nama":"KAFA BANGUNAN KHAS KG RAJUNAH","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5332/S10019": {"nama":"KAFA BANGUNAN KHAS KG PANDASAN","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5326/S10014": {"nama":"KAFA MASJID KG TAWADAKAN","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5327/S10015": {"nama":"KAFA SURAU KG KESAPANG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5331/S10018": {"nama":"KAFA MASJID KG TAMBILAUNG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5315/S10006": {"nama":"KAFA MASJID KG KAWANG-KAWANG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYQ5317/S10004": {"nama":"KAFA SAR LASAU PODI","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5329/S10017": {"nama":"KAFA MASJID KG TEKULUNG","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5319/S10008": {"nama":"KAFA SURAU KG WANI","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5322/S10011": {"nama":"KAFA SURAU KG LOMPIOS","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "XYT5333/S10020": {"nama":"KAFA MASJID KG ROSOK","daerah":"KOTA BELUD 3","negeri":"SABAH"},
  "SIMPANAN-KOTA-BELUD-3": {"nama":"SIMPANAN DAERAH","daerah":"KOTA BELUD 3","negeri":"SABAH"},
    "XBA5101/S12001": {"nama":"KAFA SK PEKAN LAMA","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5113/S12010": {"nama":"KAFA TAMBUN LAUT 1","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5103/S12005": {"nama":"KAFA TAMBUN LAUT 2","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5291/S12023": {"nama":"KAFA ASA-SOLEHIN","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5108/S12008": {"nama":"KAFA KORONGKOM","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XBA5117/S12002": {"nama":"KAFA SK ONGKILAN","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5102/S12004": {"nama":"KAFA GARUDA","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5116/S12012": {"nama":"KAFA KG.RASAK LAUT","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5106/S12007": {"nama":"KAFA KG.RANAU","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XBA5110/S12022": {"nama":"KAFA SK TAGAROH","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5105/S12006": {"nama":"KAFA AL-FARABI","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5115/S12011": {"nama":"KAFA SURAU KG.TIMBANG BATU","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5119/S12015": {"nama":"KAFA AS-SIDDIQ","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5101/S12003": {"nama":"KAFA SIMPANGAN","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5112/S12009": {"nama":"KAFA LOTONG","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5117/S12013": {"nama":"KAFA SUNSUI","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5251/S12020": {"nama":"KAFA AL-AZEEM","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5243/S12018": {"nama":"KAFA KHAS MUHIBBAH","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5248/S12019": {"nama":"KAFA BINGKONGAN DARAT","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "XYT5257/S12021": {"nama":"KAFA SURAU LANGKON BARU","daerah":"KOTA MARUDU","negeri":"SABAH"},
  "SIMPANAN-KOTA-MARUDU": {"nama":"SIMPANAN DAERAH","daerah":"KOTA MARUDU","negeri":"SABAH"},
    "XYP63012 / S13002": {"nama":"SAN PEKAN KUALA PENYU (KAFA)","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6307 / S13012": {"nama":"KAFA KG LINSUK","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6301 / S13006": {"nama":"KAFA MASJID NURUL HAYAT PEKAN KUALA PENYU","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYP6304 / S13003": {"nama":"KAFA SAN PALU-PALU","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6306 / S13011": {"nama":"KAFA BALAI BOMBA","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6308 / S13013": {"nama":"KAFA KG BADUNGUN KUALA PENYU","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYP6306 / S13004": {"nama":"SAN KG KERUKAN KUALA PENYU (KAFA)","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6305 / S13010": {"nama":"KAFA KG KEKAPOR","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6081 / S13001": {"nama":"KAFA KG MENUNGGANG","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6304 / S13009": {"nama":"KAFA KG BERANGKOK","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6311 / S13016": {"nama":"KAFA KG TEMPURONG","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYQ6301 / S13005": {"nama":"KAFA SAR MELIKAI","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6335 / S13018": {"nama":"KAFA KG BUKIT NURI MENUMBOK","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6303 / S13008": {"nama":"KAFA KG TANJUNG ARU","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6340 / S13020": {"nama":"KAFA KG JAGUS","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XBA6308 / S13022": {"nama":"KAFA SK LAMBIDAN","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6302 / S13007": {"nama":"KAFA KG MEMPAKUL MENUMBOK","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6314 / S13017": {"nama":"KAFA KG SEKALONG","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6309 / S13014": {"nama":"KAFA KG KILUGUS","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "XYT6310 / S13015": {"nama":"KAFA MASJID KG SIAUN MENUMBOK","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
  "SIMPANAN-KUALA-PENYU": {"nama":"SIMPANAN DAERAH","daerah":"KUALA PENYU DAN MENUMBOK","negeri":"SABAH"},
    "XBA4014 / S11001": {"nama":"KAFA SURAU SK KEPAYAN","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYQ4001 / S11004": {"nama":"KAFA MADRASAH AL MUBARAK","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYQ4004 / S11006": {"nama":"KAFA SAR AL-AZHAR","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYQ4014 / S11008": {"nama":"KAFA SAR ANNUR CAHAYAKU","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4001 / S11009": {"nama":"KAFA KG CENDERAKASIH KOLOMBONG","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4003 / S11011": {"nama":"KAFA TAMAN KERAMAT","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4024 / S11014": {"nama":"KAFA RUMAH PERSEKUTUAN","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYQ4002 / S11005": {"nama":"MADRASAH HADHANAH","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYQ4011 / S11007": {"nama":"KAFA SAR NURUL HIKMAH BUKIT PADANG","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4023 / S11013": {"nama":"KAFA PERUMAHAN HOSPITAL MESRA BUKIT PADANG","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XBA4020 / S11002": {"nama":"KAFA SK KOLOMBONG","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4025 / S11015": {"nama":"KAFA MADRASAH ISLAMIAH NURUL ISLAM KOTA KINABALU","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4004 / S11012": {"nama":"KAFA TABIKA PERPADUAN KEPAYAN RIDGE","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4002 / S11010": {"nama":"KAFA KG PULAU GAYA ASLI","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT4026 / S11016": {"nama":"KAFA KASUAPAN PULAU GAYA","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "XYT6084 / S11017": {"nama":"KAFA ANNUR IMAN KG TORONG LOGONG, PULAU GAYA ASLI","daerah":"KOTA KINABALU","negeri":"SABAH"},
  "SIMPANAN-KOTA-KINABALU": {"nama":"SIMPANAN DAERAH","daerah":"KOTA KINABALU","negeri":"SABAH"},
  
});
