Object.assign(window.SCHOOLS, {
  "K04001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ASAM JAWA","negeri":"KEDAH","daerah":"BALING"},
"K04002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BADANG","negeri":"KEDAH","daerah":"BALING"},
"K04003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BALING","negeri":"KEDAH","daerah":"BALING"},
"K04004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BATU PEKAKA","negeri":"KEDAH","daerah":"BALING"},
"K04005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN BINJUL DALAM","negeri":"KEDAH","daerah":"BALING"},
"K04006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BINJUL LUAR","negeri":"KEDAH","daerah":"BALING"},
"K04007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN DALAM WANG","negeri":"KEDAH","daerah":"BALING"},
"K04008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN IBOI","negeri":"KEDAH","daerah":"BALING"},
"K04009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN KAMPONG BANDAR","negeri":"KEDAH","daerah":"BALING"},
"K04010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN SERA","negeri":"KEDAH","daerah":"BALING"},
"K04011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPONG PADANG","negeri":"KEDAH","daerah":"BALING"},
"K04012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN KAMPONG KEDA","negeri":"KEDAH","daerah":"BALING"},
"K04013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KUALA KETIL","negeri":"KEDAH","daerah":"BALING"},
"K04014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KUALA KUANG","negeri":"KEDAH","daerah":"BALING"},
"K04015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KUALA MERAH","negeri":"KEDAH","daerah":"BALING"},
"K04016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KUALA PEGANG","negeri":"KEDAH","daerah":"BALING"},
"K04017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KUALA SAMAK","negeri":"KEDAH","daerah":"BALING"},
"K04018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN LANAI","negeri":"KEDAH","daerah":"BALING"},
"K04019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN MALAU","negeri":"KEDAH","daerah":"BALING"},
"K04020": {"rujukan":"20","nama":"SEKOLAH KHAS BALING","negeri":"KEDAH","daerah":"BALING"},
"K04021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN MOHD ARIFF ABDULLAH","negeri":"KEDAH","daerah":"BALING"},
"K04022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN PAYA BESAR","negeri":"KEDAH","daerah":"BALING"},
"K04023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN PENGHULU ABU BAKAR","negeri":"KEDAH","daerah":"BALING"},
"K04024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN PULAI","negeri":"KEDAH","daerah":"BALING"},
"K04025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN RAMBONG PULAI","negeri":"KEDAH","daerah":"BALING"},
"K04026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN SEBERANG KETIL","negeri":"KEDAH","daerah":"BALING"},
"K04027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN SELARONG","negeri":"KEDAH","daerah":"BALING"},
"K04028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAN SERI BAYU","negeri":"KEDAH","daerah":"BALING"},
"K04029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN SERI INAS BAKAI","negeri":"KEDAH","daerah":"BALING"},
"K04030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN SERI JEMERLI","negeri":"KEDAH","daerah":"BALING"},
"K04031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN SIONG","negeri":"KEDAH","daerah":"BALING"},
"K04032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN SYED SHEH","negeri":"KEDAH","daerah":"BALING"},
"K04033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN TANJUNG PARI","negeri":"KEDAH","daerah":"BALING"},
"K04034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN TAWAR","negeri":"KEDAH","daerah":"BALING"},
"K04035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN TIAK","negeri":"KEDAH","daerah":"BALING"},
"K04036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN TITI GANTUNG","negeri":"KEDAH","daerah":"BALING"},
"K04037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN TELOI KANAN","negeri":"KEDAH","daerah":"BALING"},
"K04038": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN TELOK TEDURI","negeri":"KEDAH","daerah":"BALING"},
"K04039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN TEMBAK","negeri":"KEDAH","daerah":"BALING"},
"K04040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN TUNKU PUAN HABSAH","negeri":"KEDAH","daerah":"BALING"},
"K04041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN TUNKU PUTERA","negeri":"KEDAH","daerah":"BALING"},
"K04042": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN ULU BAKAI","negeri":"KEDAH","daerah":"BALING"},
"K04043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN ULU TAWAR","negeri":"KEDAH","daerah":"BALING"},
"K04044": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN KAMPONG SADEK","negeri":"KEDAH","daerah":"BALING"},
"K04045": {"rujukan":"45","nama":"SEKOLAH KEBANGSAAN KUALA KUPANG","negeri":"KEDAH","daerah":"BALING"},
"K04046": {"rujukan":"46","nama":"KAFA SEKOLAH RENDAH ISLAM DARUL HIJRAH","negeri":"KEDAH","daerah":"BALING"},
"K04047": {"rujukan":"47","nama":"MADRASAH ISLAHIAH DINIAH","negeri":"KEDAH","daerah":"BALING"},
"K04048": {"rujukan":"48","nama":"SRITI DARUL ULUM","negeri":"KEDAH","daerah":"BALING"},
"K04049": {"rujukan":"49","nama":"SMA DINIAH ISLAMIAH","negeri":"KEDAH","daerah":"BALING"},
"K04049": {"rujukan":"50","nama":"SRA DINIAH ISLAMIAH","negeri":"KEDAH","daerah":"BALING"},
"K04050": {"rujukan":"51","nama":"SEKOLAH RENDAH TAHFIZ SAINS AL FALAH","negeri":"KEDAH","daerah":"BALING"},
"K04051": {"rujukan":"52","nama":"MAAHAD TAFAQQUH FIDDIN AN-NUR","negeri":"KEDAH","daerah":"BALING"},
"K04052": {"rujukan":"53","nama":"SEKOLAH RENDAH ISLAM RAUDHATUL MUSLIMIN","negeri":"KEDAH","daerah":"BALING"},
"SIMPANAN-BALING": {"rujukan":"54","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"BALING"},
"K11001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN SUNGAI BATU","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN SUNGAI TAKA","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SUNGAI TENGAS","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN SELAMA","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN SUNGAI SALLEH","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN JALAN SELAMA","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN DATO' HJ.ZAINUDDIN","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN AYER PUTEH","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN LUBOK BUNTAR","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN PERMATANG KERAT TELUNJUK","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN SUNGAI KECHIL ULU","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11012": {"rujukan":"12","nama":"KAFA MASJID AL-AMAN","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN BANDAR BAHARU","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN PERMATANG PASIR","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11015": {"rujukan":"15","nama":"KAFA MASJID SUNGAI KECHIL ILIR","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K11016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN RELAU","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"SIMPANAN-BANDAR-BAHARU": {"rujukan":"17","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"BANDAR BAHARU"},
"K01001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ALOR JANGGUS","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN ALOR MENGKUDU","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN ALOR MELINTANG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN ALOR SETAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN BUKIT PINANG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BULUH LIMA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BOHOR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN DATO' WAN MOHAMAD SAMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN DATO' SHAARI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN DARUL HIKMAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPONG GELAM","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN GERIGIS","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN GUNONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN HAJI ISMAIL","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN HAJI HASSAN ITAM","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN HAJI IDRIS TAJAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN HAJI ABDULLAH SADUN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN HAJI SALLEH MASRI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN HAJI ABU BAKAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN HAJI WAHAB","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN ISKANDAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN JALAN PEGAWAI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN KAMPONG JAWA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN KEBUN PINANG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN KOTA RENTANG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN KUBANG TEDUH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN KANGKONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN KUALA KEDAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN LENGKUAS","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN LAHAR BUDI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN LANGGAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN PERMATANG GUNUNG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN PEREMBA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN SRI GUNONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN SRI MAHAWANGSA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN SRI TAMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN SERI PANTAI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01038": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN SIMPANG TIGA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN SEBERANG PERAK BARU","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN SEBERANG PERAK","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN SUNGAI KOROK LAMA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01042": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN SUNGAI BARU","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN SUKA MENANTI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01044": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN TELAGA MAS","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01045": {"rujukan":"45","nama":"SEKOLAH KEBANGSAAN TELOK KECHAI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01046": {"rujukan":"46","nama":"SEKOLAH KEBANGSAAN TEBENGAU","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01047": {"rujukan":"47","nama":"SEKOLAH KEBANGSAAN TAMAN BERSATU","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01048": {"rujukan":"48","nama":"SEKOLAH KEBANGSAAN TITI GAJAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01049": {"rujukan":"49","nama":"SEKOLAH KEBANGSAAN TUNKU RAUDZAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01050": {"rujukan":"50","nama":"SEKOLAH KEBANGSAAN TAMAN AWANA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01051": {"rujukan":"51","nama":"SEKOLAH KEBANGSAAN TAMAN AMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01052": {"rujukan":"52","nama":"SEKOLAH KEBANGSAAN WAN SULAIMAN SIDIQ","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01053": {"rujukan":"53","nama":"KAFA SURAU JALAN FAJAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01056": {"rujukan":"54","nama":"KAFA MASJID KAMPUNG BERJAYA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01057": {"rujukan":"55","nama":"KAFA SURAU TAMAN WIRA MERGONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01058": {"rujukan":"56","nama":"KAFA SURAU AL FALAH TAMAN GOLF","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01059": {"rujukan":"57","nama":"KAFA SURAU TAMAN RAKYAT","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01060": {"rujukan":"58","nama":"SEKOLAH AGAMA AS-SIBYAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01061": {"rujukan":"59","nama":"KAFA MASJID AS SOLIHIN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01062": {"rujukan":"60","nama":"KAFA MASJID AMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01063": {"rujukan":"61","nama":"KAFA MASJID GUNUNG SALI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01064": {"rujukan":"62","nama":"KAFA MASJID JAMEK HUTAN KAMPONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01065": {"rujukan":"63","nama":"KAFA MASJID UBUDIYYAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01066": {"rujukan":"64","nama":"KAFA MASJID SYED MOHAMMAD AL BUKHARY PANTAI JOHOR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01067": {"rujukan":"65","nama":"KAFA MASJID NURUL IMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01068": {"rujukan":"66","nama":"KAFA ASSIDDIQ","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01069": {"rujukan":"67","nama":"KAFA PUSAT DAKWAH ISLAM KEDAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01070": {"rujukan":"68","nama":"KAFA SWASTA SEKOLAH RENDAH AN NAJAAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01071": {"rujukan":"69","nama":"SEKOLAH KEBANGSAAN JALAN DATUK KUMBAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01072": {"rujukan":"70","nama":"SEKOLAH RENDAH ISLAM DARUL AMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01073": {"rujukan":"71","nama":"SEKOLAH RENDAH ISLAM UMMI (SERU)","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01074": {"rujukan":"72","nama":"SEKOLAH RENDAH ISLAM ALOR SETAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01075": {"rujukan":"73","nama":"SEK. REN. INTEGRASI TERAS ISLAM DARUL AMAN","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01076": {"rujukan":"74","nama":"SRITI TAHFIZ AT-TAKLIMIAH ALOR SETAR","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01077": {"rujukan":"75","nama":"SEKOLAH RENDAH ISLAM DARUL ULUM","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01078": {"rujukan":"76","nama":"PUSAT PEMBELAJARAN AL-QURAN DAN AKHLAK (ILHAM) KAFA SWASTA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01079": {"rujukan":"77","nama":"SEKOLAH RENDAH ISLAM TAHFIZ DARUL HIDAYAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01080": {"rujukan":"78","nama":"SEKOLAH KEBANGSAAN SERI PERDANA","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01081": {"rujukan":"79","nama":"KAFA SWASTA TAMAN SYED MOHAMED","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01082": {"rujukan":"80","nama":"KAFA SWASTA MASJID AL BUKHARY, ALOR MALAI","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K01083": {"rujukan":"81","nama":"SEKOLAH KEBANGSAAN MERGONG","negeri":"KEDAH","daerah":"KOTA SETAR"},
"SIMPANAN-KOTA-SETAR": {"rujukan":"82","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"KOTA SETAR"},
"K02001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN BATU HAMPAR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02003": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BERAPIT","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02004": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BUKIT MERIAM","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02005": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BUKIT KECHIL KOTA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02006": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN DATARAN MUDA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02007": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN DARUL AMAN BUKIT KECHIK SIMPOR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02009": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN HAJI OMAR TAHIR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02011": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN KAMPONG PASIR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02012": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN KAMPUNG KUALA SIN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02013": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN KOTA KUALA MUDA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02014": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KEM LAPANGAN TERBANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02015": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN MERBOK (PUSAT)","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02016": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN PANTAI PRAI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02017": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN PINANG TUNGGAL","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02018": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN RANTAU PANJANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02020": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN SERI GEDONG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02022": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SERI KUALA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02023": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SERI WANGSA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02024": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN SEMELING","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02025": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN SIDAM KIRI PADANG SERAI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02026": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN SIMPOR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02027": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN SUNGAI LAYAR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02028": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN SUNGKAP PARA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02029": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN TANJUNG DAWAI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02030": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN TIKAM BATU","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02031": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN TUNKU ISMAIL","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02032": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN TELOK WANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02033": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN LAGUNA MERBOK","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02034": {"rujukan":"29","nama":"KAFA MASJID AL- AMIN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02035": {"rujukan":"30","nama":"KAFA MASJID SUNGAI LALANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02036": {"rujukan":"31","nama":"KAFA MASJID KAMPUNG BUJANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02037": {"rujukan":"32","nama":"KAFA MASJID AL-MUTTAQIN TAMAN RIA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02038": {"rujukan":"33","nama":"KAFA MASJID BATU 3 JALAN JENIANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02040": {"rujukan":"34","nama":"KAFA AT TAHIR MASJID KAMPUNG SUNGAI GELAM","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02041": {"rujukan":"35","nama":"KAFA MASJID BAKAR ARANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02042": {"rujukan":"36","nama":"KAFA MASJID AL-WAJDI BUKIT SELAMBAU","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02043": {"rujukan":"37","nama":"KAFA SURAU SALMAN AL-FARISI BANDAR PUTERI JAYA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02044": {"rujukan":"38","nama":"KAFA SURAU KAMPUNG BUKIT","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02045": {"rujukan":"39","nama":"KAFA SURAU TAMAN KELADI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02046": {"rujukan":"40","nama":"KAFA SURAU AL-HIDAYAH TAMAN RIA JAYA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02047": {"rujukan":"41","nama":"KAFA MASJID AL-MUHAJIRIN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02048": {"rujukan":"42","nama":"KAFA SURAU TAMAN SERI PINANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02049": {"rujukan":"43","nama":"PUSAT KAFA BANDAR AMANJAYA DAERAH KUALA MUDA KEDAH DARUL AMAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02051": {"rujukan":"44","nama":"KAFA SURAU KAMPUNG BERJAYA, JENIANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02052": {"rujukan":"45","nama":"KAFA SURAU TAMAN SUTERA JAYA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02053": {"rujukan":"46","nama":"KAFA SURAU TAMAN PERUDA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02054": {"rujukan":"47","nama":"KAFA SURAU PERWAJA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02055": {"rujukan":"48","nama":"KAFA SURAU TAMAN DESA ENGGANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02056": {"rujukan":"49","nama":"KAFA SURAU TAMAN SERI WANG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02057": {"rujukan":"50","nama":"KAFA SURAU TAMAN KELISA RIA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02058": {"rujukan":"51","nama":"KAFA SURAU BANDAR PERDANA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02059": {"rujukan":"52","nama":"KAFA SURAU AN-NUR ZON MAWAR","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02060": {"rujukan":"53","nama":"KAFA AS SYAKIRIN MASJID HJ KUDUNG","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02062": {"rujukan":"54","nama":"KAFA SURAU KAMPUNG KUBANG BEMBAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02064": {"rujukan":"55","nama":"KAFA SURAU PENJARA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02065": {"rujukan":"56","nama":"KAFA SURAU AS SALAM BANDAR SERI ASTANA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02067": {"rujukan":"57","nama":"KAFA MASJID BATU 5","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02069": {"rujukan":"58","nama":"SEKOLAH KEBANGSAAN PETANI JAYA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02071": {"rujukan":"59","nama":"SEKOLAH KEBANGSAAN KHIR JOHARI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02072": {"rujukan":"60","nama":"SEKOLAH KEBANGSAAN TAMAN INTAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02073": {"rujukan":"61","nama":"KAFA SWASTA AL-IKHWAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02074": {"rujukan":"62","nama":"SEKOLAH RENDAH AGAMA RUHUL MANNAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02075": {"rujukan":"63","nama":"KAFA SWASTA SURAU AN NUR RAMADHAN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02076": {"rujukan":"64","nama":"KAFA SWASTA MASJID SULTAN ABDUL HALIM","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02077": {"rujukan":"65","nama":"KAFA SWASTA MASJID AL-MUHSININ KAMPUNG RAJA","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02078": {"rujukan":"66","nama":"KAFA SWASTA SURAU AL-AMIN","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02079": {"rujukan":"67","nama":"SR AKADEMI ISLAM HAJI ABDULLAH SUBOH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02080": {"rujukan":"68","nama":"SEKOLAH RENDAH AL-ISLAH, SUNGAI PETANI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02081": {"rujukan":"69","nama":"SEKOLAH RENDAH ISLAM AL-MAARIF (SERI SUNGAI PETANI)","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02082": {"rujukan":"70","nama":"SEKOLAH RENDAH ISLAM AL IHSANIAH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02083": {"rujukan":"71","nama":"KAFA SWASTA AL-HIDAYAH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02084": {"rujukan":"72","nama":"SRA ZUBAIDIYAH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02085": {"rujukan":"73","nama":"SMART TAHFIZ DARUL BAYAN (STADY)","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02086": {"rujukan":"74","nama":"KAFA SWASTA ANDALUSIA BANDAR LAGUNA MERBOK","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02087": {"rujukan":"75","nama":"SEKOLAH RENDAH AGAMA DARIS","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02088": {"rujukan":"76","nama":"SEKOLAH RENDAH AGAMA INTEGRASI TAHFIZ AL-FATEEH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K02089": {"rujukan":"77","nama":"KAFA SWASTA WILDAN BESTARI","negeri":"KEDAH","daerah":"KUALA MUDA"},
"SIMPANAN-KUALA-MUDA": {"rujukan":"78","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"KUALA MUDA"},
"K03001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN KEPALA BATAS","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BUKIT TINGGI","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN ANAK ANGKATAN TENTERA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN SERI BANAI","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN PENGHULU HAJI DARUS","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BANDAR BARU DARULAMAN","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN JITRA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN JITRA II","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN JITRA 3","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN SULTAN AHMAD TAJUDDIN","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN GELONG","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN MALAU","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN BINJAL","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN HOSBA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN GUAR NAPAI","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN DATO' WAN KEMARA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN BUKIT TANGGA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN BANDAR BARU SINTOK","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN BANDAR BUKIT KAYU HITAM","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN FELDA LAKA SELATAN","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN BATU 8","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN TUNKU BENDAHARA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN KODIANG","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN SIPUTEH","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN PADANG PERAHU","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN TUNJANG","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN PULAU NYIOR","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN HAKIM TEH","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN TELOK MALEK","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN SERI MUDA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN JERLUN","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN AYER HITAM","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN MATANG PAKU","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN TUNKU LAKSAMANA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN PULAU CHAPA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN PIDA TIGA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN MEGAT DEWA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03038": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN MANGGOL BONGOR","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN TOK KEPAK","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN DATO' SRI SYED AHMAD","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN SANGLANG","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03042": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN HAJI WAN YAHYA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN DATO' SYED NAHAR","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03044": {"rujukan":"44","nama":"KAFA AL-BUKHARI MASJID KAMPUNG BUKIT","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03045": {"rujukan":"45","nama":"KAFA AN-NUR MASJID KAMPUNG DARAT","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03046": {"rujukan":"46","nama":"SEKOLAH KEBANGSAAN PADANG PEKAN","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03047": {"rujukan":"47","nama":"KAFA SURAU KEM KELUBI","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03048": {"rujukan":"48","nama":"SEKOLAH KEBANGSAAN PAYA KEMUNTING","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03049": {"rujukan":"49","nama":"KAFA PUSAT ISLAM UUM","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03050": {"rujukan":"50","nama":"SEKOLAH KEBANGSAAN PUTAT","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03051": {"rujukan":"51","nama":"SEKOLAH KEBANGSAAN DARULAMAN HEIGHTS","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03052": {"rujukan":"52","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM (SRITI) AN-NUR","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03053": {"rujukan":"53","nama":"SEKOLAH RENDAH AL-AZHAR","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03054": {"rujukan":"54","nama":"SEKOLAH AGAMA AT-TOYYIBAH","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03055": {"rujukan":"55","nama":"KAFA UUM INTERNATIONAL SCHOOL","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K03056": {"rujukan":"56","nama":"SRITI AL FATEH KAMPUNG RAJA","negeri":"KEDAH","daerah":"KUBANG PASU"},
"SIMPANAN-KUBANG-PASU": {"rujukan":"57","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"KUBANG PASU"},
"K05001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN GUAR LOBAK","negeri":"KEDAH","daerah":"KULIM"},
"K05002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN LABU BESAR","negeri":"KEDAH","daerah":"KULIM"},
"K05003": {"rujukan":"3","nama":"KAFA MASJID SUNGAI KARANGAN","negeri":"KEDAH","daerah":"KULIM"},
"K05004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BUKIT SELARONG","negeri":"KEDAH","daerah":"KULIM"},
"K05005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN MERBAU PULAS","negeri":"KEDAH","daerah":"KULIM"},
"K05006": {"rujukan":"6","nama":"KAFA MASJID ABDUL HALIM MUADZAM SHAH","negeri":"KEDAH","daerah":"KULIM"},
"K05007": {"rujukan":"7","nama":"KAFA MASJID NURUSSAADAH","negeri":"KEDAH","daerah":"KULIM"},
"K05008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN JALAN PAYA BESAR KULIM","negeri":"KEDAH","daerah":"KULIM"},
"K05009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN JUNJONG","negeri":"KEDAH","daerah":"KULIM"},
"K05010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN PERMATANG TIONG","negeri":"KEDAH","daerah":"KULIM"},
"K05011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN TERAP","negeri":"KEDAH","daerah":"KULIM"},
"K05012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN SUNGAI KOB","negeri":"KEDAH","daerah":"KULIM"},
"K05013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN LADANG DUBLIN","negeri":"KEDAH","daerah":"KULIM"},
"K05014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN GUNUNG BONGSU","negeri":"KEDAH","daerah":"KULIM"},
"K05015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN MAHANG","negeri":"KEDAH","daerah":"KULIM"},
"K05016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN LADANG BUKIT SEDIM","negeri":"KEDAH","daerah":"KULIM"},
"K05017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SERI LINDUNGAN RAJA","negeri":"KEDAH","daerah":"KULIM"},
"K05018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN AIR MERAH","negeri":"KEDAH","daerah":"KULIM"},
"K05019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN PAGAR MUSEH","negeri":"KEDAH","daerah":"KULIM"},
"K05020": {"rujukan":"20","nama":"KAFA MASJID AN-NAJAH PADANG SERAI","negeri":"KEDAH","daerah":"KULIM"},
"K05021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN TAMAN HI TECH","negeri":"KEDAH","daerah":"KULIM"},
"K05022": {"rujukan":"22","nama":"KAFA NURUL ILMI","negeri":"KEDAH","daerah":"KULIM"},
"K05023": {"rujukan":"23","nama":"KAFA MASJID KELADI","negeri":"KEDAH","daerah":"KULIM"},
"K05024": {"rujukan":"24","nama":"KAFA MASJID KULIM","negeri":"KEDAH","daerah":"KULIM"},
"K05025": {"rujukan":"25","nama":"KAFA ALHUDA MASJID KELANG LAMA","negeri":"KEDAH","daerah":"KULIM"},
"K05026": {"rujukan":"26","nama":"KAFA MASJID BAGAN SENA","negeri":"KEDAH","daerah":"KULIM"},
"K05027": {"rujukan":"27","nama":"KAFA MASJID BADLISHAH","negeri":"KEDAH","daerah":"KULIM"},
"K05028": {"rujukan":"28","nama":"KAFA MASJID AIR MERAH","negeri":"KEDAH","daerah":"KULIM"},
"K05029": {"rujukan":"29","nama":"KAFA MASJID SUNGAI ULAR","negeri":"KEDAH","daerah":"KULIM"},
"K05030": {"rujukan":"30","nama":"KAFA AL-KAUTHAR MASJID TUNKU ABDUL RAHMAN PUTRA","negeri":"KEDAH","daerah":"KULIM"},
"K05031": {"rujukan":"31","nama":"KAFA SURAU KAMPUNG PADANG TEMBAK","negeri":"KEDAH","daerah":"KULIM"},
"K05032": {"rujukan":"32","nama":"KAFA SURAU TAMAN ANGSANA","negeri":"KEDAH","daerah":"KULIM"},
"K05033": {"rujukan":"33","nama":"KAFA SURAU TAMAN KUCHAI","negeri":"KEDAH","daerah":"KULIM"},
"K05034": {"rujukan":"34","nama":"KAFA SURAU PASUKAN GERAKAN AM","negeri":"KEDAH","daerah":"KULIM"},
"K05035": {"rujukan":"35","nama":"KAFA MASJID TAMAN KENARI","negeri":"KEDAH","daerah":"KULIM"},
"K05036": {"rujukan":"36","nama":"KAFA SURAU ASY-SYAKIRIN","negeri":"KEDAH","daerah":"KULIM"},
"K05037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN TAMAN MUTIARA","negeri":"KEDAH","daerah":"KULIM"},
"K05038": {"rujukan":"38","nama":"KAFA MADRASAH DARUL MUMTAZ","negeri":"KEDAH","daerah":"KULIM"},
"K05039": {"rujukan":"39","nama":"KAFA AL HAMRA","negeri":"KEDAH","daerah":"KULIM"},
"K05040": {"rujukan":"40","nama":"KAFA MASJID AL MUTTAQIN TAMAN SELASIH","negeri":"KEDAH","daerah":"KULIM"},
"K05041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN TAMAN JELUTONG","negeri":"KEDAH","daerah":"KULIM"},
"K05042": {"rujukan":"42","nama":"KAFA MASJID SAIDINA UMAR AL-KHATTAB","negeri":"KEDAH","daerah":"KULIM"},
"K05043": {"rujukan":"43","nama":"PUSAT PENDIDIKAN ISLAM KAFA NURUL HIDAYAH","negeri":"KEDAH","daerah":"KULIM"},
"K05044": {"rujukan":"44","nama":"SRITI IBNU KHALDUN BANDAR PUTRA KULIM","negeri":"KEDAH","daerah":"KULIM"},
"K05045": {"rujukan":"45","nama":"SEK. REN. INTEGRASI TERAS ISLAM IBNU UMAR","negeri":"KEDAH","daerah":"KULIM"},
"K05046": {"rujukan":"46","nama":"SEKOLAH RENDAH ISLAM AL-ISLAH KULIM","negeri":"KEDAH","daerah":"KULIM"},
"K05047": {"rujukan":"47","nama":"SEKOLAH RENDAH ISLAM NURUL HIDAYAH PENGHULU ELANG","negeri":"KEDAH","daerah":"KULIM"},
"K05048": {"rujukan":"48","nama":"SEK. REN. ISLAM RAUDHATUL JANNAH","negeri":"KEDAH","daerah":"KULIM"},
"K05049": {"rujukan":"49","nama":"SRITI AL-FATEH KULIM","negeri":"KEDAH","daerah":"KULIM"},
"K05050": {"rujukan":"50","nama":"SEKOLAH TAHFIZ SAINS AN NAJIHIN (RENDAH)","negeri":"KEDAH","daerah":"KULIM"},
"K05051": {"rujukan":"51","nama":"MAAHAD TARBIAH MUSLIM NUSANTARA","negeri":"KEDAH","daerah":"KULIM"},
"K05052": {"rujukan":"52","nama":"KAFA SWASTA MASJID AL MUTHMAINNAH (GHAIRU JAMEK)","negeri":"KEDAH","daerah":"KULIM"},
"K05054": {"rujukan":"53","nama":"KAFA SWASTA IMDAD QURANIC CENTRE","negeri":"KEDAH","daerah":"KULIM"},
"K05055": {"rujukan":"54","nama":"KAFA SWASTA DARUL HANA","negeri":"KEDAH","daerah":"KULIM"},
"SIMPANAN-KULIM": {"rujukan":"55","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"KULIM"},
"KBA6013": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN LANGKAWI","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6006": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN SERI NEGERI","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6010": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SERI LAGENDA","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6022": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN KILIM","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBE6005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN KELIBANG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6002": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BAYAS","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6004": {"rujukan":"7","nama":"SEKOLAH KEBANGSAANKEDAWANG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6011": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN TEMONYONG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBE6001": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN PENGHULU AHMAD","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6012": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN ULU MELAKA","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6021": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN NYIOR CHABANG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6008": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN PADANG MATSIRAT","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6007": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KUALA TERIANG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6009": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN PULAU TUBA","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6020": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN SELAT BAGAN NYIOR","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA6001": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN LUBUK CEMPEDAK","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6020": {"rujukan":"17","nama":"KAFA SURAU IBU PEJABAT POLIS","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6025": {"rujukan":"18","nama":"KAFA SURAUCHANDEK KURA","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6011": {"rujukan":"19","nama":"KAFA MASJID EWA","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6010": {"rujukan":"20","nama":"KAFA MASJID KELIBANG","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6016": {"rujukan":"21","nama":"KAFA MASJID YOOI","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYT6001": {"rujukan":"22","nama":"KAFA MASJID AISYAH, SUNGAI MENGHULU","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYR6002": {"rujukan":"23","nama":"SEKOLAH RENDAH ISLAM AL-KHAIRIE","negeri":"KEDAH","daerah":"LANGKAWI"},
"KYR6001": {"rujukan":"24","nama":"SEKOLAH RENDAH ISLAM DARUL ULUM","negeri":"KEDAH","daerah":"LANGKAWI"},
"SIMPANAN-LANGKAWI": {"rujukan":"25","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"LANGKAWI"},
"KBA7001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN BUKIT TEMBAGA","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN KUALA NERANG","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KURONG HITAM","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN TOH PUAN SHARIFAH HANIFAH","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN NAKA","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN PANGLIMA AWANG","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN NAMI","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN PADANG SANAI","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN PADANG TERAP","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN TANDOP BESAR","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN DATIN FATIMAH","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN PEDU","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KAMPONG BELUKAR","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN TUALAK","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN LUBOK MERBAU","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN PERIK","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7019": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KUBANG PALAS","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBA7020": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SERI BAKTI","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KBB7016": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN TUNKU ABDUL RAHMAN PUTRA","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KYR7002": {"rujukan":"20","nama":"SRITI NURUL HIDAYAH PEKAN NAKA","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KYR7003": {"rujukan":"21","nama":"SEKOLAH RENDAH ISLAM AL-FATEH","negeri":"KEDAH","daerah":"PADANG TERAP"},
"KYT7001": {"rujukan":"22","nama":"SEKOLAH RENDAH ISLAM AL-KHAIRIAH","negeri":"KEDAH","daerah":"PADANG TERAP"},
"SIMPANAN-PADANG-TERAP": {"rujukan":"23","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"PADANG TERAP"},
"K06001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN AYER PUTEH","negeri":"KEDAH","daerah":"PENDANG"},
"K06002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN ALOR BESAR","negeri":"KEDAH","daerah":"PENDANG"},
"K06003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BUKIT GENTING","negeri":"KEDAH","daerah":"PENDANG"},
"K06004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BUKIT CHORAS","negeri":"KEDAH","daerah":"PENDANG"},
"K06005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN BUKIT RAYA DALAM","negeri":"KEDAH","daerah":"PENDANG"},
"K06006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BUKIT JAMBUL","negeri":"KEDAH","daerah":"PENDANG"},
"K06007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BUKIT JENUN","negeri":"KEDAH","daerah":"PENDANG"},
"K06008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN BENDANG RAJA","negeri":"KEDAH","daerah":"PENDANG"},
"K06009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN CHAROK KUDONG","negeri":"KEDAH","daerah":"PENDANG"},
"K06010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN GUAR KEPAYANG","negeri":"KEDAH","daerah":"PENDANG"},
"K06011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN HUJUNG KETON","negeri":"KEDAH","daerah":"PENDANG"},
"K06012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN HAJI MAT DAHAN","negeri":"KEDAH","daerah":"PENDANG"},
"K06013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN HAJI MOHAMAD ARIFF","negeri":"KEDAH","daerah":"PENDANG"},
"K06014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN HAJI ABDUL RAHMAN","negeri":"KEDAH","daerah":"PENDANG"},
"K06015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KAMPONG RAMBAI","negeri":"KEDAH","daerah":"PENDANG"},
"K06016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KAMPONG CHEGAR","negeri":"KEDAH","daerah":"PENDANG"},
"K06017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KAMPUNG BARU","negeri":"KEDAH","daerah":"PENDANG"},
"K06018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN KUALA RIMAU","negeri":"KEDAH","daerah":"PENDANG"},
"K06019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN KUBOR PANJANG","negeri":"KEDAH","daerah":"PENDANG"},
"K06020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN POKOK ASAM","negeri":"KEDAH","daerah":"PENDANG"},
"K06021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN POKOK TAI","negeri":"KEDAH","daerah":"PENDANG"},
"K06022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN SYED IBRAHIM","negeri":"KEDAH","daerah":"PENDANG"},
"K06023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN PADANG DURIAN","negeri":"KEDAH","daerah":"PENDANG"},
"K06024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN PAYA MENGKUANG","negeri":"KEDAH","daerah":"PENDANG"},
"K06025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN PAYA MAK INSON","negeri":"KEDAH","daerah":"PENDANG"},
"K06026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN PAYA RAWA","negeri":"KEDAH","daerah":"PENDANG"},
"K06027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN KAMPUNG PULAI","negeri":"KEDAH","daerah":"PENDANG"},
"K06028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN PENDANG","negeri":"KEDAH","daerah":"PENDANG"},
"K06029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN PENGHULU JUSOH","negeri":"KEDAH","daerah":"PENDANG"},
"K06030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN SUNGAI TIANG","negeri":"KEDAH","daerah":"PENDANG"},
"K06031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN SUNGAI SIPUT","negeri":"KEDAH","daerah":"PENDANG"},
"K06032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN TANAH MERAH","negeri":"KEDAH","daerah":"PENDANG"},
"K06033": {"rujukan":"33","nama":"SEKOLAH MODEL KHAS BUKIT JENUN","negeri":"KEDAH","daerah":"PENDANG"},
"K06034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN TUNKU INTAN SAFINAZ","negeri":"KEDAH","daerah":"PENDANG"},
"K06035": {"rujukan":"35","nama":"SEKOLAH RENDAH ISLAM TARBIAH AL-AWLADIAH","negeri":"KEDAH","daerah":"PENDANG"},
"K06036": {"rujukan":"36","nama":"SEKOLAH RENDAH ISLAM ISLAH","negeri":"KEDAH","daerah":"PENDANG"},
"K06037": {"rujukan":"37","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM TARBIYATUL AULAD","negeri":"KEDAH","daerah":"PENDANG"},
"SIMPANAN-PENDANG": {"rujukan":"38","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"PENDANG"},
"K12001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN WAN ABDUL SAMAD","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN KAMPUNG BUKIT","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KUALA LANJUT","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BUKIT TAMPOI","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN JABI","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN NAWA","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN TELUK JAMAT","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN TUALANG","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN BUKIT PAYONG","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN BUKIT HIJAU","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPONG PAYA","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN KUBANG LERET","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN POKOK SENA","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN BUKIT PAK KIAU","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12015": {"rujukan":"15","nama":"RUMAH KANAK-KANAK POKOK SENA","negeri":"KEDAH","daerah":"POKOK SENA"},
"K12016": {"rujukan":"16","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM (SRITI) RAUDHATU AS-SOLIHIN","negeri":"KEDAH","daerah":"POKOK SENA"},
"SIMPANAN-POKOK-SENA": {"rujukan":"17","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"POKOK SENA"},
"K09001 ": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN BANDAR BARU BERIS JAYA","negeri":"KEDAH","daerah":"SIK"},
"K09002 ": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BATU LIMA SIK","negeri":"KEDAH","daerah":"SIK"},
"K09003 ": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BATU 8","negeri":"KEDAH","daerah":"SIK"},
"K09004 ": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN CHEMARA SIK","negeri":"KEDAH","daerah":"SIK"},
"K09005 ": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN CHEPIR","negeri":"KEDAH","daerah":"SIK"},
"K09006 ": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN DANGLAU","negeri":"KEDAH","daerah":"SIK"},
"K09007 ": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN GULAU","negeri":"KEDAH","daerah":"SIK"},
"K09008 ": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN HAJI HUSSAIN","negeri":"KEDAH","daerah":"SIK"},
"K09009 ": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN HUJUNG BANDAR","negeri":"KEDAH","daerah":"SIK"},
"K09010 ": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN JENERI","negeri":"KEDAH","daerah":"SIK"},
"K09011 ": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KALAI","negeri":"KEDAH","daerah":"SIK"},
"K09012 ": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN KAMPUNG BETONG","negeri":"KEDAH","daerah":"SIK"},
"K09013 ": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KOTA AUR","negeri":"KEDAH","daerah":"SIK"},
"K09014 ": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAMPONG KOTA BUKIT","negeri":"KEDAH","daerah":"SIK"},
"K09015 ": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN PAYA TERENDAM","negeri":"KEDAH","daerah":"SIK"},
"K09016 ": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN PADANG CHICHAK","negeri":"KEDAH","daerah":"SIK"},
"K09017 ": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SERI AMPANG MUDA","negeri":"KEDAH","daerah":"SIK"},
"K09018 ": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SERI DUSUN","negeri":"KEDAH","daerah":"SIK"},
"K09019 ": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN SIK","negeri":"KEDAH","daerah":"SIK"},
"K09020 ": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN SIK DALAM","negeri":"KEDAH","daerah":"SIK"},
"K09021 ": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN TELOI TIMUR","negeri":"KEDAH","daerah":"SIK"},
"K09022 ": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN TELOI TUA","negeri":"KEDAH","daerah":"SIK"},
"K09023 ": {"rujukan":"23","nama":"SEKOLAH JENIS KEBANGSAAN (C) CHUNG HWA","negeri":"KEDAH","daerah":"SIK"},
"K09025 ": {"rujukan":"24","nama":"MAAHAD AL-TARBIAH AL-ISLAMIAH AL-WATANIAH (PONDOK BEGIA)","negeri":"KEDAH","daerah":"SIK"},
"K09026 ": {"rujukan":"25","nama":"DARUL QURAN WA AT-TARBIAH AL-MUNIR","negeri":"KEDAH","daerah":"SIK"},
"SIMPANAN-SIK": {"rujukan":"26","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"SIK"},
"KBA3001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN GURUN PUSAT","negeri":"KEDAH","daerah":"YAN"},
"KBA3002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN JENIANG","negeri":"KEDAH","daerah":"YAN"},
"KBA3008": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BEDONG","negeri":"KEDAH","daerah":"YAN"},
"KBB3038": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN SERI AMAN","negeri":"KEDAH","daerah":"YAN"},
"KBA3011": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN SRI JERAI","negeri":"KEDAH","daerah":"YAN"},
"KBA9022": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN HJ HUSSIN DOL","negeri":"KEDAH","daerah":"YAN"},
"KBA9001": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN GUAR CHEMPEDAK","negeri":"KEDAH","daerah":"YAN"},
"KBA9002": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN PADANG LUMAT","negeri":"KEDAH","daerah":"YAN"},
"KBA9003": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN SUNGAI KERING","negeri":"KEDAH","daerah":"YAN"},
"KBA9004": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN SUNGAI LIMAU","negeri":"KEDAH","daerah":"YAN"},
"KBA9005": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN HJ KASSIM JASIN","negeri":"KEDAH","daerah":"YAN"},
"KBA9006": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN ULU SEDAKA","negeri":"KEDAH","daerah":"YAN"},
"KBA9007": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN DULANG","negeri":"KEDAH","daerah":"YAN"},
"KBA9008": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAMPUNG PAUH","negeri":"KEDAH","daerah":"YAN"},
"KBA9009": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KAMPONG SETAR","negeri":"KEDAH","daerah":"YAN"},
"KBA9010": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN LANGKASUKA","negeri":"KEDAH","daerah":"YAN"},
"KBA9011": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN TOK MAT SALLEH","negeri":"KEDAH","daerah":"YAN"},
"KBA9012": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN TEROI","negeri":"KEDAH","daerah":"YAN"},
"KBA9013": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN YAN KECHIL","negeri":"KEDAH","daerah":"YAN"},
"KBA9014": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN HJ NYAK GAM","negeri":"KEDAH","daerah":"YAN"},
"KBA9016": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN BUKIT BESAR","negeri":"KEDAH","daerah":"YAN"},
"KBA9017": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN PERMATANG BULOH","negeri":"KEDAH","daerah":"YAN"},
"KBA9018": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN SUNGAI DEDAP","negeri":"KEDAH","daerah":"YAN"},
"KBA9019": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN SIMPANG TIGA SUNGAI DAUN","negeri":"KEDAH","daerah":"YAN"},
"KBA9020": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN SUNGAI DAUN TENGAH","negeri":"KEDAH","daerah":"YAN"},
"KBA9021": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN SINGKIR","negeri":"KEDAH","daerah":"YAN"},
"KYT9001": {"rujukan":"27","nama":"KAFA MASJID TITI TERAS","negeri":"KEDAH","daerah":"YAN"},
"KYR9001": {"rujukan":"28","nama":"SRA AL-AKHLAK AL-ISLAMIAH","negeri":"KEDAH","daerah":"YAN"},
"KYR9002": {"rujukan":"29","nama":"SRI TAHFIZ IBNU ABBAS","negeri":"KEDAH","daerah":"YAN"},
"SIMPANAN-YAN": {"rujukan":"30","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"YAN"},

  "R03001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN FELDA RIMBA MAS","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN SERI TUNJONG","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN PADANG BESAR UTARA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN CHUPING","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN PAYA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN GUAR NANGKA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN PANGGAS","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN DATO' KAYAMAN","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN LUBUK SIREH","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN BESERI","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN BUKIT KETERI","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN PADANG MELANGIT","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN ORAN","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN FELDA CHUPING","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03015": {"rujukan":"15","nama":"SEKOLAH RENDAH ISLAM III FELDA CHUPING","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN SANTAN","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03018": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN GUAR JENTIK","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03019": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN TITI TINGGI","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03020": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN BATU BERTANGKUP","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03021": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN FELDA MATA AIR","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03022": {"rujukan":"21","nama":"SEKOLAH RENDAH ISLAM AT-TAQWA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03023": {"rujukan":"22","nama":"SEK.REN ISLAM II FELDA MATA AIR","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03024": {"rujukan":"23","nama":"SEK. REN. AGAMA ATTARBIYAH AL-ISLAMIYAH (SRAATI)","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03025": {"rujukan":"24","nama":"SJKC KONG AIK","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03026": {"rujukan":"25","nama":"SJKC KONG HWA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03027": {"rujukan":"26","nama":"SJKC PADANG BESAR UTARA","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R03028": {"rujukan":"27","nama":"PUSAT KOREKSIONAL PENJARA PERLIS","negeri":"PERLIS","daerah":"PADANG BESAR"},
"SIMPANAN-PADANG-BESAR": {"rujukan":"28","nama":"SIMPANAN DAERAH","negeri":"PERLIS","daerah":"PADANG BESAR"},
"R02001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN SERI PERLIS","negeri":"PERLIS","daerah":"KANGAR"},
"R02002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BEHOR EMPIANG","negeri":"PERLIS","daerah":"KANGAR"},
"R02003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SENA","negeri":"PERLIS","daerah":"KANGAR"},
"R02004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN UTAN AJI","negeri":"PERLIS","daerah":"KANGAR"},
"R02005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN JEJAWI","negeri":"PERLIS","daerah":"KANGAR"},
"R02006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KAMPONG SALANG","negeri":"PERLIS","daerah":"KANGAR"},
"R02007": {"rujukan":"7","nama":"SEKOLAH RENDAH KEBANGSAAN STELLA MARRIS","negeri":"PERLIS","daerah":"KANGAR"},
"R02008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN BINTONG","negeri":"PERLIS","daerah":"KANGAR"},
"R02009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN PADANG KOTA","negeri":"PERLIS","daerah":"KANGAR"},
"R02010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN PADANG BESAR SELATAN","negeri":"PERLIS","daerah":"KANGAR"},
"R02011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KUALA PERLIS","negeri":"PERLIS","daerah":"KANGAR"},
"R02012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN JALAN RAJA SYED ALWI","negeri":"PERLIS","daerah":"KANGAR"},
"R02013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN UJONG BATU","negeri":"PERLIS","daerah":"KANGAR"},
"R02014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAYANG","negeri":"PERLIS","daerah":"KANGAR"},
"R02015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN ABI","negeri":"PERLIS","daerah":"KANGAR"},
"R02016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN DATO' WAN AHMAD","negeri":"PERLIS","daerah":"KANGAR"},
"R02017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SEBERANG RAMAI","negeri":"PERLIS","daerah":"KANGAR"},
"R02018": {"rujukan":"18","nama":"SEKOLAH RENDAH KEBANGSAAN SERI INDERA","negeri":"PERLIS","daerah":"KANGAR"},
"R02019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN PUTRA","negeri":"PERLIS","daerah":"KANGAR"},
"R02020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN PANGGAU","negeri":"PERLIS","daerah":"KANGAR"},
"R02021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN TITI TOK BANDAR","negeri":"PERLIS","daerah":"KANGAR"},
"R02023": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN IPGM","negeri":"PERLIS","daerah":"KANGAR"},
"R02024": {"rujukan":"23","nama":"SEKOLAH RENDAH ISLAM 1, ABI","negeri":"PERLIS","daerah":"KANGAR"},
"R02025": {"rujukan":"24","nama":"SEKOLAH RENDAH ISLAM AL-FURQAN","negeri":"PERLIS","daerah":"KANGAR"},
"R02026": {"rujukan":"25","nama":"SEK. REN. ISLAM MITHALI AQRAB","negeri":"PERLIS","daerah":"KANGAR"},
"R02027": {"rujukan":"26","nama":"SJKC KHOON AIK","negeri":"PERLIS","daerah":"KANGAR"},
"R02028": {"rujukan":"27","nama":"SJKC CHOON SIEW,KUALA PERLIS","negeri":"PERLIS","daerah":"KANGAR"},
"R02029": {"rujukan":"28","nama":"SJK(C) KHAY BENG","negeri":"PERLIS","daerah":"KANGAR"},
"R02030": {"rujukan":"29","nama":"TERATAK RAHMAT (AL-ISLAH)","negeri":"PERLIS","daerah":"KANGAR"},
"SIMPANAN-KANGAR": {"rujukan":"30","nama":"SIMPANAN DAERAH","negeri":"PERLIS","daerah":"KANGAR"},
"R01001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ARAU","negeri":"PERLIS","daerah":"ARAU"},
"R01002": {"rujukan":"2","nama":"SEKOLAH RENDAH AGAMA AL - ISLAHIYAH","negeri":"PERLIS","daerah":"ARAU"},
"R01003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SANGLANG","negeri":"PERLIS","daerah":"ARAU"},
"R01004": {"rujukan":"4","nama":"SEKOLAH TENGKU BUDRIAH","negeri":"PERLIS","daerah":"ARAU"},
"R01005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN SIMPANG EMPAT","negeri":"PERLIS","daerah":"ARAU"},
"R01006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KAMPONG SERDANG","negeri":"PERLIS","daerah":"ARAU"},
"R01007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN CHANGKAT JAWI","negeri":"PERLIS","daerah":"ARAU"},
"R01008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN DATO AHMAD MUSA","negeri":"PERLIS","daerah":"ARAU"},
"R01009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN SUNGAI BARU","negeri":"PERLIS","daerah":"ARAU"},
"R01010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN TAMBUN TULANG","negeri":"PERLIS","daerah":"ARAU"},
"R01011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN RAJA PEREMPUAN BUDRIAH","negeri":"PERLIS","daerah":"ARAU"},
"R01012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN PADANG KERIA","negeri":"PERLIS","daerah":"ARAU"},
"R01013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN PAUH","negeri":"PERLIS","daerah":"ARAU"},
"R01014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN JELEMPOK","negeri":"PERLIS","daerah":"ARAU"},
"R01015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN LONG BOH","negeri":"PERLIS","daerah":"ARAU"},
"R01016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN BOHOR MALI","negeri":"PERLIS","daerah":"ARAU"},
"R01017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KUBANG GAJAH","negeri":"PERLIS","daerah":"ARAU"},
"R01018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SUNGAI BEREMBANG","negeri":"PERLIS","daerah":"ARAU"},
"R01019": {"rujukan":"19","nama":"SEK. REN. ISLAM AL-AZHAR","negeri":"PERLIS","daerah":"ARAU"},
"R01020": {"rujukan":"20","nama":"SJKC SIN MIN","negeri":"PERLIS","daerah":"ARAU"},
"R01022": {"rujukan":"21","nama":"SKJ(C) SIMPANG EMPAT","negeri":"PERLIS","daerah":"ARAU"},
"R01023": {"rujukan":"22","nama":"SJKC HWA AIK","negeri":"PERLIS","daerah":"ARAU"},
"SIMPANAN-ARAU": {"rujukan":"23","nama":"SIMPANAN DAERAH","negeri":"PERLIS","daerah":"ARAU"},

  "A09001": {"rujukan":"1","nama":"SRAR NOR HIDAYAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09002": {"rujukan":"2","nama":"SRAR IRSYADIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09003": {"rujukan":"3","nama":"SRAR AL-TAHZIB","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09004": {"rujukan":"4","nama":"SRAR AL-FALAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09005": {"rujukan":"5","nama":"SRAR KHAIRIAH ISLAMIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09006": {"rujukan":"6","nama":"SRAR AL-TAUFIQIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09007": {"rujukan":"7","nama":"SRAR AL IBTIDAIAH ADDINIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09010": {"rujukan":"8","nama":"SRAR NURKAMALIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09011": {"rujukan":"9","nama":"SRAR AL-ISLAMIAH BATU 11","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09012": {"rujukan":"10","nama":"SRAR RAUDATUL ISLAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09013": {"rujukan":"11","nama":"SRAR AL-HIDAYAH ADDINIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09016": {"rujukan":"12","nama":"SRAR ILMAN WAL IRFAN (P.T.B)","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09017": {"rujukan":"13","nama":"SRAR AL-NAJAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09019": {"rujukan":"14","nama":"SRAR MUHAMMADIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09020": {"rujukan":"15","nama":"SRAR AL-EHYA' ADDINIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09021": {"rujukan":"16","nama":"SRAR TARBIAH ISLAMIAH  B. TIANG","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09024": {"rujukan":"17","nama":"SRAR AL-HIDAYATUL ISLAMIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09022": {"rujukan":"18","nama":"SRI AL HASANAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09026": {"rujukan":"19","nama":"SRAR AL FURQAN","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09027": {"rujukan":"20","nama":"SRAR AL-AMANIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09009": {"rujukan":"21","nama":"SRAR AL-AZIZIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09015": {"rujukan":"22","nama":"SRAR NURHIDAYAH KUALA GULA","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09018": {"rujukan":"23","nama":"SRAR NURUL IMAN","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09008": {"rujukan":"24","nama":"SRAR AL-ISLAMIAH ADDINIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09014": {"rujukan":"25","nama":"SRAR FADILAH ISLAMIAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A09023": {"rujukan":"26","nama":"SRAR ASMAWIYAH KEDAI 4","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"SIMPANAN-PARIT-BUNTAR": {"rujukan":"27","nama":"SIMPANAN DAERAH","negeri":"PERAK","daerah":"PARIT BUNTAR"},
"A 010 01": {"rujukan":"1","nama":"MADRASAH AL-AZHARUL JANNAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 02": {"rujukan":"2","nama":"MADRASAH TARBIAH ADDINIAH AL-ISLAMIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 14": {"rujukan":"3","nama":"MADRASAH IBTIDAIAH ADDINIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 13": {"rujukan":"4","nama":"SRAR LATIFIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 10": {"rujukan":"5","nama":"SRAR AL-AMMAR","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 11": {"rujukan":"6","nama":"MADRASAH ATTARBIAH ADDINIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 12": {"rujukan":"7","nama":"SRAR NURUL HUDA","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 31": {"rujukan":"8","nama":"SRI AL EHYA' ASSHARIFF","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 27": {"rujukan":"9","nama":"MADRASAH ISLAMIAH ADDINIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 03": {"rujukan":"10","nama":"MADRASAH TAUFIKIAH AL-DINIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 28": {"rujukan":"11","nama":"SRAR UBUDIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 32": {"rujukan":"12","nama":"SRAR AL-FAIZIN","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 04": {"rujukan":"13","nama":"SRAR DIDIKAN AGAMA","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 19": {"rujukan":"14","nama":"SRAR ARBAIYAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 23": {"rujukan":"15","nama":"SRAR AN-NUR","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 15": {"rujukan":"16","nama":"SRAR AL-TAIYIBAH AL-MANSORIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 17": {"rujukan":"17","nama":"MADRASAH AL-ISLAHIYAH AD-DINIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 18": {"rujukan":"18","nama":"SRAR RAUDHATUL JANNAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 16": {"rujukan":"19","nama":"SRAR AN-NAJAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 06": {"rujukan":"20","nama":"SRAR AL-AKHLAK AL-ISLAMIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 33": {"rujukan":"21","nama":"SRITI BESTARI","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 20": {"rujukan":"22","nama":"SRAR NOORHIDAYAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 21": {"rujukan":"23","nama":"SRAR AL-HIDAYAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 24": {"rujukan":"24","nama":"SRAR NURUL ISLAMIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 22": {"rujukan":"25","nama":"SRAR NURUL HIDAYAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 26": {"rujukan":"26","nama":"MADRASAH RAUDATUL NAJAHIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 25": {"rujukan":"27","nama":"SRAR JANNATUS SUNNAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 29": {"rujukan":"28","nama":"SRAR NURUL KHAIRIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 05": {"rujukan":"29","nama":"SRAR NURUL NAJWA","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 30": {"rujukan":"30","nama":"SRA AR-RIDHWANIAH","negeri":"PERAK","daerah":"BAGAN SERAI"},
"A 010 09": {"rujukan":"31","nama":"SRAR NURUL IMAN","negeri":"PERAK","daerah":"BAGAN SERAI"},
"SIMPANAN-BAGAN-SERAI": {"rujukan":"32","nama":"SIMPANAN DAERAH","negeri":"PERAK","daerah":"BAGAN SERAI"},

  
  });            
