window.SCHOOLS = {
"WPKL001": {"rujukan":"1","nama":"KAFA SURAU KG. BELUKUT","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL002": {"rujukan":"2","nama":"KAFA SURAU PERUMAHAN LDA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL003": {"rujukan":"3","nama":"KAFA BAITUL HIDAYAH, FLAT JKR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL004": {"rujukan":"4","nama":"KAFA AL-ROSHIDAH KG. KIAMSAM WAWASAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL005": {"rujukan":"5","nama":"KAFA MASJID SIRAJUL ISLAM, TANJUNG ARU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL006": {"rujukan":"6","nama":"KAFA ADZ-DZIKRULLAH KG RANCHA-RANCHA LAUT.","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL007": {"rujukan":"7","nama":"KAFA SURAU KG. BATU MANIKAR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL008": {"rujukan":"8","nama":"KAFA AL-EHSANIAH KG. MUSLIM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL009": {"rujukan":"9","nama":"KAFA QURRATUL 'AIN KAMPUNG LAJAU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL010": {"rujukan":"10","nama":"KAFA NUR IMAN MASJID NUR IMAN, KG. GANGGARAK","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL011": {"rujukan":"11","nama":"KAFA AL-HIDAYAH KG. KIAMSAM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL012": {"rujukan":"12","nama":"KAFA SURAU AR-RAUDHAH, KG. BUKIT KUDA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL013": {"rujukan":"13","nama":"KAFA NUR HIKMAH SURAU KG. KILAN KASSIM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL014": {"rujukan":"14","nama":"KAFA SURAU AL-IRSYAD, KG. KILAN PULAU AKAR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL015": {"rujukan":"15","nama":"KAFA SURAU UWAIS ALQARNI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL016": {"rujukan":"16","nama":"KAFA AL-HIDAYAH MASJID AL-MUNAWWAR KG. POHON BATU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL017": {"rujukan":"17","nama":"KAFA DARUL FURQOON BALAI RAYA KG. GERSIK","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL018": {"rujukan":"18","nama":"KAFA JANNATUL AN-NAIM, MASJID AL-MUTTAKIN IOFC KERUPANG","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL019": {"rujukan":"19","nama":"KAFA AS-SHOBIRIN KG.BARU PULAU DA'AT","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKS031": {"rujukan":"20","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM (SRITI) LABUAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKS038": {"rujukan":"21","nama":"MADRASAH AL HAQ WP LABUAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL001": {"rujukan":"22","nama":"SRA ATTARBIAH AL ISLAMIAH PEKAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL002": {"rujukan":"23","nama":"SRA DARUL ULUM MEMBEDAI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL003": {"rujukan":"24","nama":"SRA AL-AHMADIAH PATAU-PATAU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL004": {"rujukan":"25","nama":"SRA NURUTTAQWA RANCHA-RANCHA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL005": {"rujukan":"26","nama":"SRA AL- LAMUDIN KG SG BEDAUN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL006": {"rujukan":"27","nama":"SRA ABU BAKAR BEBULOH","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL007": {"rujukan":"28","nama":"SRA AT-TAUFIQIAH SUNGAI MIRI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL008": {"rujukan":"29","nama":"SRA NURUL HIDAYAH LAYANG-LAYANGAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL009": {"rujukan":"30","nama":"SRA NURUL FALAH BUKIT KALAM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL010": {"rujukan":"31","nama":"SEKOLAH INTEGRASI RENDAH AGAMA JAWI (SIRAJ) SAIDINA UMAR AL-KHATTAB","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"SIMPANAN-LABUAN": {"rujukan":"32","nama":"SIMPANAN DAERAH","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},

"J01001": {"rujukan":"1","nama":"SEKOLAH AGAMA SUNGAI TIRAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01002": {"rujukan":"2","nama":"SEKOLAH AGAMA TAMAN BUKIT TIRAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01003": {"rujukan":"3","nama":"SEKOLAH AGAMA BANDAR TIRAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01004": {"rujukan":"4","nama":"SEKOLAH AGAMA FELDA ULU TEBRAU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01005": {"rujukan":"5","nama":"SEKOLAH AGAMA DATO' ABDULLAH ESA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01006": {"rujukan":"6","nama":"SEKOLAH AGAMA TAMAN DAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01007": {"rujukan":"7","nama":"SEKOLAH AGAMA TAMAN JOHOR JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01008": {"rujukan":"8","nama":"SEKOLAH AGAMA TAMAN DESA JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01009": {"rujukan":"9","nama":"SEKOLAH AGAMA DESA CEMERLANG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01010": {"rujukan":"10","nama":"SEKOLAH AGAMA KANGKAR TEBRAU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01011": {"rujukan":"11","nama":"SEKOLAH AGAMA ASY-SYA'RAWI TAMAN MOUNT AUSTIN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01012": {"rujukan":"12","nama":"SEKOLAH AGAMA TAMAN ANGGERIK","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01013": {"rujukan":"13","nama":"SEKOLAH AGAMA TAMAN IMPIAN EMAS","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01014": {"rujukan":"14","nama":"SEKOLAH AGAMA KAMPUNG MAJU JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01015": {"rujukan":"15","nama":"SEKOLAH AGAMA MAJIDEE BARU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01016": {"rujukan":"16","nama":"SEKOLAH AGAMA DATO' SULAIMAN MENTERI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01017": {"rujukan":"17","nama":"SEKOLAH AGAMA KAMPUNG MELAYU PANDAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01018": {"rujukan":"18","nama":"SEKOLAH AGAMA TAMAN CEMPAKA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01019": {"rujukan":"19","nama":"SEKOLAH AGAMA TAMAN DAHLIA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01020": {"rujukan":"20","nama":"SEKOLAH AGAMA KEMPAS BARU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01021": {"rujukan":"21","nama":"SEKOLAH AGAMA TAMAN MOLEK","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01022": {"rujukan":"22","nama":"SEKOLAH AGAMA TAMAN GAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01023": {"rujukan":"23","nama":"SEKOLAH AGAMA TAMAN PUTERI WANGSA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01024": {"rujukan":"24","nama":"SEKOLAH AGAMA TAMAN SETIA INDAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01025": {"rujukan":"25","nama":"SEKOLAH AGAMA PASIR GUDANG 1","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01026": {"rujukan":"26","nama":"SEKOLAH AGAMA PASIR GUDANG 2","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01027": {"rujukan":"27","nama":"SEKOLAH AGAMA KAMPUNG PASIR PUTIH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01028": {"rujukan":"28","nama":"SEKOLAH AGAMA TAMAN RINTING","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01029": {"rujukan":"29","nama":"SEKOLAH AGAMA TAMAN MAWAR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01030": {"rujukan":"30","nama":"SEKOLAH AGAMA TUN HUSSEIN ONN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01031": {"rujukan":"31","nama":"SEKOLAH AGAMA BANDAR PERMAS JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01032": {"rujukan":"32","nama":"SEKOLAH AGAMA DATO' HJ ABDUL RAHMAN AHMAD","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01033": {"rujukan":"33","nama":"SEKOLAH AGAMA AS-SYAKIRIN MASAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01034": {"rujukan":"34","nama":"SEKOLAH AGAMA SENIBONG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01035": {"rujukan":"35","nama":"SEKOLAH AGAMA TANJUNG LANGSAT","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01036": {"rujukan":"36","nama":"SEKOLAH AGAMA KONGKONG LAUT","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01037": {"rujukan":"37","nama":"SEKOLAH AGAMA KAMPUNG PERIGI ACHEH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01038": {"rujukan":"38","nama":"SEKOLAH AGAMA KOPOK BARU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01039": {"rujukan":"39","nama":"SEKOLAH AGAMA TAMAN PASIR PUTIH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01040": {"rujukan":"40","nama":"SEKOLAH AGAMA BANDAR SERI ALAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01041": {"rujukan":"41","nama":"SEKOLAH AGAMA AL IMTIYAZ SERI KOTA PUTERI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01042": {"rujukan":"42","nama":"SEKOLAH AGAMA TAMAN CENDANA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01043": {"rujukan":"43","nama":"SEKOLAH AGAMA TAMAN KOTA MASAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01044": {"rujukan":"44","nama":"SEKOLAH AGAMA PERMAS JAYA 5","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01045": {"rujukan":"45","nama":"SEKOLAH AGAMA TAMAN SCIENTEX","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01046": {"rujukan":"46","nama":"SEKOLAH AGAMA TAMAN KOTA MASAI 2","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01047": {"rujukan":"47","nama":"SEKOLAH AGAMA DATO' OMAR YUSOF","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01048": {"rujukan":"48","nama":"SEKOLAH AGAMA UNGKU MOHAMAD","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01049": {"rujukan":"49","nama":"SEKOLAH AGAMA PUAN HAJAH RAHMAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01050": {"rujukan":"50","nama":"SEKOLAH AGAMA TAMAN PELANGI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01051": {"rujukan":"51","nama":"SEKOLAH AGAMA F.R.U","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01052": {"rujukan":"52","nama":"SEKOLAH AGAMA DATO' ONN JAAFAR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01053": {"rujukan":"53","nama":"SEKOLAH AGAMA BANDAR JOHOR BAHRU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01054": {"rujukan":"54","nama":"SEKOLAH AGAMA KAMPUNG AMAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01055": {"rujukan":"55","nama":"SEKOLAH AGAMA KAMPUNG KASTAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01056": {"rujukan":"56","nama":"SEKOLAH AGAMA TAMBATAN TINGGI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01057": {"rujukan":"57","nama":"SEKOLAH AGAMA PRINCESS ELIZABETH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01058": {"rujukan":"58","nama":"SEKOLAH AGAMA TASEK UTARA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01059": {"rujukan":"59","nama":"SEKOLAH AGAMA BANDAR BARU UDA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01060": {"rujukan":"60","nama":"SEKOLAH AGAMA IBNU KHALDUN, TAMAN PERLING 1","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01061": {"rujukan":"61","nama":"SEKOLAH AGAMA TAMAN PERLING 2","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01062": {"rujukan":"62","nama":"SEKOLAH AGAMA PERUMAHAN MARA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01063": {"rujukan":"63","nama":"SEKOLAH AGAMA SUNGAI DANGA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01064": {"rujukan":"64","nama":"SEKOLAH AGAMA KEBUN TEH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01065": {"rujukan":"65","nama":"SEKOLAH AGAMA BUKIT INDAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01066": {"rujukan":"66","nama":"SEKOLAH AGAMA GELANG PATAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01067": {"rujukan":"67","nama":"SEKOLAH AGAMA TANJUNG KUPANG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01068": {"rujukan":"68","nama":"SEKOLAH AGAMA DESA PAYA MENGKUANG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01069": {"rujukan":"69","nama":"SEKOLAH AGAMA TAMAN UNGKU TUN AMINAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01070": {"rujukan":"70","nama":"SEKOLAH AGAMA AN-NUR BATU 10 SKUDAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01071": {"rujukan":"71","nama":"SEKOLAH AGAMA TAMAN UNIVERSITI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01072": {"rujukan":"72","nama":"SEKOLAH AGAMA KOMPLEKS SULTAN ABU BAKAR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01073": {"rujukan":"73","nama":"SEKOLAH AGAMA KENANGAN MORNI POK","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01074": {"rujukan":"74","nama":"SEKOLAH AGAMA TAMAN SKUDAI BARU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01075": {"rujukan":"75","nama":"SEKOLAH AGAMA LIMA KEDAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01076": {"rujukan":"76","nama":"SEKOLAH AGAMA BANDAR SELESA JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01077": {"rujukan":"77","nama":"SEKOLAH AGAMA TIRAM DUKU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01078": {"rujukan":"78","nama":"SEKOLAH AGAMA KAMPUNG PULAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01079": {"rujukan":"79","nama":"SEKOLAH AGAMA TEBING RUNTUH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01080": {"rujukan":"80","nama":"SEKOLAH AGAMA PENDAS LAUT","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01081": {"rujukan":"81","nama":"SEKOLAH AGAMA SUNGAI MELAYU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01082": {"rujukan":"82","nama":"SEKOLAH AGAMA NUSA PERINTIS 1","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01083": {"rujukan":"83","nama":"SEKOLAH AGAMA TAMAN MUTIARA RINI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01084": {"rujukan":"84","nama":"SEKOLAH AGAMA NUSANTARA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01085": {"rujukan":"85","nama":"SEKOLAH AGAMA SIMPANG ARANG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01086": {"rujukan":"86","nama":"SEKOLAH AGAMA TAMAN UNIVERSITI 2","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01087": {"rujukan":"87","nama":"SEKOLAH AGAMA MEDINI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01088": {"rujukan":"88","nama":"SEKOLAH AGAMA TAMAN DAMAI JAYA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01089": {"rujukan":"89","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) JOHOR BAHRU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01090": {"rujukan":"90","nama":"SEKOLAH RENDAH ISLAM JOHOR BAHRU","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01091": {"rujukan":"91","nama":"SEKOLAH RENDAH AGAMA DAN TAHFIZ AL-QURAN DARUL IRFAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01092": {"rujukan":"92","nama":"SEKOLAH RENDAH ISLAM PINTAR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01093": {"rujukan":"93","nama":"SEKOLAH RENDAH ISLAM AT TAHFIZ","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01094": {"rujukan":"94","nama":"MAAHAD TAHFIZ AL-IMAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01095": {"rujukan":"95","nama":"SEKOLAH AGAMA TAMAN BUKIT MEWAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01097": {"rujukan":"96","nama":"SEKOLAH RENDAH ISLAM AL-AZHAR (PERLING 1)","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01098": {"rujukan":"97","nama":"MAAHAD TAHFIZ AL QURAN RIYADUS SOLIHIN (MATARAS)","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01099": {"rujukan":"98","nama":"SEKOLAH RENDAH ISLAM & TAHFIZ AL-QURAN WAWASAN AL-IRFAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01100": {"rujukan":"99","nama":"SEKOLAH AGAMA TAMAN BUKIT DAHLIA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01101": {"rujukan":"100","nama":"SEKOLAH AGAMA TAMAN BUKIT MUTIARA","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01102": {"rujukan":"101","nama":"SEKOLAH AGAMA TAMAN CAHAYA MASAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01103": {"rujukan":"102","nama":"SEKOLAH AGAMA TAMAN NUSA DAMAI","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01104": {"rujukan":"103","nama":"SEKOLAH RENDAH ISLAM AL-AKHYAR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01105": {"rujukan":"104","nama":"SEKOLAH AGAMA BANDAR SERI ALAM 2","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01106": {"rujukan":"105","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL-KAUTHAR, PASIR GUDANG","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01107": {"rujukan":"106","nama":"SEKOLAH RENDAH ISLAM I-QURANIC CENTER","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01108": {"rujukan":"107","nama":"ACADEMY DARUL HUFFAZ JOHOR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01109": {"rujukan":"108","nama":"SEKOLAH RENDAH ISLAM AL-AZHAR ( ULU TIRAM )","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01110": {"rujukan":"109","nama":"SEKOLAH RENDAH ISLAM AR-RASYIDIN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01111": {"rujukan":"110","nama":"MADRASAH TAHFIZ BUSTANUL JANNAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01112": {"rujukan":"111","nama":"SEKOLAH RENDAH ISLAM AL-AZHAR (BANDAR SERI ALAM)","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01113": {"rujukan":"112","nama":"SEKOLAH RENDAH ISLAM AL IHSAN","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01114": {"rujukan":"113","nama":"MADRASAH TAHFIZ HUDA AL- ISLAM","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01116": {"rujukan":"114","nama":"MAAHAD TAHFIZ DAR ABSYIR","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01117": {"rujukan":"115","nama":"SEKOLAH RENDAH ISLAM MUTIARA AR RAUDHAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01118": {"rujukan":"116","nama":"SEKOLAH RENDAH ISLAM AL JANNAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01119": {"rujukan":"117","nama":"SEKOLAH RENDAH ISLAM AL-AZHAR ( NUSANTARA )","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01120": {"rujukan":"118","nama":"SEKOLAH RENDAH ISLAM AL-AZHAR ( TAMAN UNIVERSITI)","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01121": {"rujukan":"119","nama":"SEKOLAH RENDAH ISLAM TUNAS KHALIFAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J01122": {"rujukan":"120","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL IRSYAD","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"SIMPANAN-JOHOR-BAHRU": {"rujukan":"121","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"JOHOR BAHRU"},
"J02001": {"rujukan":"1","nama":"SEKOLAH AGAMA BANDAR MAHARANI","negeri":"JOHOR","daerah":"MUAR"},
"J02002": {"rujukan":"2","nama":"SEKOLAH AGAMA PARIT BAKAR DARAT","negeri":"JOHOR","daerah":"MUAR"},
"J02003": {"rujukan":"3","nama":"SEKOLAH AGAMA PARIT KADHI","negeri":"JOHOR","daerah":"MUAR"},
"J02004": {"rujukan":"4","nama":"SEKOLAH AGAMA PARIT KEROMA","negeri":"JOHOR","daerah":"MUAR"},
"J02005": {"rujukan":"5","nama":"SEKOLAH AGAMA PARIT KEROMA DARAT","negeri":"JOHOR","daerah":"MUAR"},
"J02006": {"rujukan":"6","nama":"SEKOLAH AGAMA PARIT RAJA","negeri":"JOHOR","daerah":"MUAR"},
"J02007": {"rujukan":"7","nama":"SEKOLAH AGAMA SERI BUKIT BATU","negeri":"JOHOR","daerah":"MUAR"},
"J02008": {"rujukan":"8","nama":"SEKOLAH AGAMA SRI JONG","negeri":"JOHOR","daerah":"MUAR"},
"J02009": {"rujukan":"9","nama":"SEKOLAH AGAMA SUNGAI ABONG","negeri":"JOHOR","daerah":"MUAR"},
"J02010": {"rujukan":"10","nama":"SEKOLAH AGAMA TUN DR ISMAIL","negeri":"JOHOR","daerah":"MUAR"},
"J02011": {"rujukan":"11","nama":"SEKOLAH AGAMA BUKIT KEPONG","negeri":"JOHOR","daerah":"MUAR"},
"J02012": {"rujukan":"12","nama":"SEKOLAH AGAMA DATO' HAJI HASSAN YUNOS","negeri":"JOHOR","daerah":"MUAR"},
"J02013": {"rujukan":"13","nama":"SEKOLAH AGAMA FELCRA BUKIT KEPONG","negeri":"JOHOR","daerah":"MUAR"},
"J02014": {"rujukan":"14","nama":"SEKOLAH AGAMA GOMBANG","negeri":"JOHOR","daerah":"MUAR"},
"J02015": {"rujukan":"15","nama":"SEKOLAH AGAMA JORAK","negeri":"JOHOR","daerah":"MUAR"},
"J02016": {"rujukan":"16","nama":"SEKOLAH AGAMA KAMPUNG RAJA","negeri":"JOHOR","daerah":"MUAR"},
"J02017": {"rujukan":"17","nama":"SEKOLAH AGAMA KAMPUNG BARU BATU 28","negeri":"JOHOR","daerah":"MUAR"},
"J02018": {"rujukan":"18","nama":"SEKOLAH AGAMA LIANG BATU","negeri":"JOHOR","daerah":"MUAR"},
"J02019": {"rujukan":"19","nama":"SEKOLAH AGAMA IBU HAMIDAH PANCHOR","negeri":"JOHOR","daerah":"MUAR"},
"J02020": {"rujukan":"20","nama":"SEKOLAH AGAMA PANJANG SARI","negeri":"JOHOR","daerah":"MUAR"},
"J02021": {"rujukan":"21","nama":"SEKOLAH AGAMA PARIT SETONGKAT","negeri":"JOHOR","daerah":"MUAR"},
"J02022": {"rujukan":"22","nama":"SEKOLAH AGAMA PAYA PANJANG","negeri":"JOHOR","daerah":"MUAR"},
"J02023": {"rujukan":"23","nama":"SEKOLAH AGAMA PAYA REDAN","negeri":"JOHOR","daerah":"MUAR"},
"J02024": {"rujukan":"24","nama":"SEKOLAH AGAMA LENGA","negeri":"JOHOR","daerah":"MUAR"},
"J02025": {"rujukan":"25","nama":"SEKOLAH AGAMA PEKAN PAGOH","negeri":"JOHOR","daerah":"MUAR"},
"J02026": {"rujukan":"26","nama":"SEKOLAH AGAMA RENCHONG","negeri":"JOHOR","daerah":"MUAR"},
"J02027": {"rujukan":"27","nama":"SEKOLAH AGAMA SEMASIH","negeri":"JOHOR","daerah":"MUAR"},
"J02028": {"rujukan":"28","nama":"SEKOLAH AGAMA SIMPANG JERAM","negeri":"JOHOR","daerah":"MUAR"},
"J02029": {"rujukan":"29","nama":"SEKOLAH AGAMA SUNGAI RAYA","negeri":"JOHOR","daerah":"MUAR"},
"J02030": {"rujukan":"30","nama":"SEKOLAH AGAMA TEMIANG","negeri":"JOHOR","daerah":"MUAR"},
"J02031": {"rujukan":"31","nama":"SEKOLAH AGAMA AIR HITAM BATU 18","negeri":"JOHOR","daerah":"MUAR"},
"J02032": {"rujukan":"32","nama":"SEKOLAH AGAMA BAKRI BATU 6","negeri":"JOHOR","daerah":"MUAR"},
"J02033": {"rujukan":"33","nama":"SEKOLAH AGAMA BUKIT NANING","negeri":"JOHOR","daerah":"MUAR"},
"J02034": {"rujukan":"34","nama":"SEKOLAH AGAMA JALAN YUSOF","negeri":"JOHOR","daerah":"MUAR"},
"J02036": {"rujukan":"35","nama":"SEKOLAH AGAMA PARIT BAKAR TENGAH","negeri":"JOHOR","daerah":"MUAR"},
"J02037": {"rujukan":"36","nama":"SEKOLAH AGAMA PARIT BULAT","negeri":"JOHOR","daerah":"MUAR"},
"J02038": {"rujukan":"37","nama":"SEKOLAH AGAMA PARIT HJ ZIN","negeri":"JOHOR","daerah":"MUAR"},
"J02039": {"rujukan":"38","nama":"SEKOLAH AGAMA PARIT JAMIL","negeri":"JOHOR","daerah":"MUAR"},
"J02040": {"rujukan":"39","nama":"SEKOLAH AGAMA PARIT JAMIL DARAT","negeri":"JOHOR","daerah":"MUAR"},
"J02041": {"rujukan":"40","nama":"SEKOLAH AGAMA PARIT JAWA","negeri":"JOHOR","daerah":"MUAR"},
"J02042": {"rujukan":"41","nama":"SEKOLAH AGAMA PARIT LATIF","negeri":"JOHOR","daerah":"MUAR"},
"J02043": {"rujukan":"42","nama":"SEKOLAH AGAMA PARIT NAWI","negeri":"JOHOR","daerah":"MUAR"},
"J02044": {"rujukan":"43","nama":"SEKOLAH AGAMA PARIT NO.5","negeri":"JOHOR","daerah":"MUAR"},
"J02045": {"rujukan":"44","nama":"SEKOLAH AGAMA PARIT PECHAH","negeri":"JOHOR","daerah":"MUAR"},
"J02046": {"rujukan":"45","nama":"SEKOLAH AGAMA PARIT PINANG SERIBU","negeri":"JOHOR","daerah":"MUAR"},
"J02047": {"rujukan":"46","nama":"SEKOLAH AGAMA NUR AS-SYAMS","negeri":"JOHOR","daerah":"MUAR"},
"J02048": {"rujukan":"47","nama":"SEKOLAH AGAMA PEKAN BARU","negeri":"JOHOR","daerah":"MUAR"},
"J02049": {"rujukan":"48","nama":"SEKOLAH AGAMA SARANG BUAYA","negeri":"JOHOR","daerah":"MUAR"},
"J02050": {"rujukan":"49","nama":"SEKOLAH AGAMA SERI MENANTI","negeri":"JOHOR","daerah":"MUAR"},
"J02051": {"rujukan":"50","nama":"SEKOLAH AGAMA SUNGAI RESIK","negeri":"JOHOR","daerah":"MUAR"},
"J02052": {"rujukan":"51","nama":"SEKOLAH AGAMA SUNGAI BALANG DARAT","negeri":"JOHOR","daerah":"MUAR"},
"J02053": {"rujukan":"52","nama":"SEKOLAH AGAMA TANJONG TOHOR","negeri":"JOHOR","daerah":"MUAR"},
"J02054": {"rujukan":"53","nama":"SEKOLAH AGAMA TAMAN PAGOH JAYA","negeri":"JOHOR","daerah":"MUAR"},
"J02055": {"rujukan":"54","nama":"SEKOLAH RENDAH AGAMA (ARAB) SAADIAH","negeri":"JOHOR","daerah":"MUAR"},
"J02056": {"rujukan":"55","nama":"SEKOLAH RENDAH AGAMA (ARAB) IRSHADUL BANAT","negeri":"JOHOR","daerah":"MUAR"},
"J02057": {"rujukan":"56","nama":"SEKOLAH RENDAH AGAMA AT-TANWIRIAH","negeri":"JOHOR","daerah":"MUAR"},
"J02058": {"rujukan":"57","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) MUAR","negeri":"JOHOR","daerah":"MUAR"},
"J02060": {"rujukan":"58","nama":"SEKOLAH AGAMA TAMAN SRI PAGOH, MUAR","negeri":"JOHOR","daerah":"MUAR"},
"J02061": {"rujukan":"59","nama":"SEKOLAH RENDAH ISLAM AT-TANWIRIAH (TAHFIZ)","negeri":"JOHOR","daerah":"MUAR"},
"SIMPANAN-MUAR": {"rujukan":"60","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"MUAR"},
"J03001": {"rujukan":"1","nama":"SEKOLAH AGAMA SERI SEPARAP","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03002": {"rujukan":"2","nama":"SEKOLAH AGAMA GAMBUT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03003": {"rujukan":"3","nama":"SEKOLAH AGAMA BAGAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03004": {"rujukan":"4","nama":"SEKOLAH AGAMA SERI CHANTEK","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03005": {"rujukan":"5","nama":"SEKOLAH AGAMA PT SULONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03006": {"rujukan":"6","nama":"SEKOLAH AGAMA SERI JASA SEPAKAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03007": {"rujukan":"7","nama":"SEKOLAH AGAMA SERI SEKAWAN DESA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03008": {"rujukan":"8","nama":"SEKOLAH AGAMA SERI MA'AMOR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03009": {"rujukan":"9","nama":"SEKOLAH AGAMA PESERAI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03010": {"rujukan":"10","nama":"SEKOLAH AGAMA KAMPUNG JAWA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03011": {"rujukan":"11","nama":"SEKOLAH AGAMA SERI UTAMA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03012": {"rujukan":"12","nama":"SEKOLAH AGAMA PESERIAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03013": {"rujukan":"13","nama":"SEKOLAH AGAMA SERI MAIMON","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03014": {"rujukan":"14","nama":"SEKOLAH AGAMA SERI MUAFAKAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03015": {"rujukan":"15","nama":"SEKOLAH AGAMA LUBOK","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03016": {"rujukan":"16","nama":"SEKOLAH AGAMA PARIT JU","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03017": {"rujukan":"17","nama":"SEKOLAH AGAMA AIR PUTEH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03018": {"rujukan":"18","nama":"SEKOLAH AGAMA SERI PENGKALAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03019": {"rujukan":"19","nama":"SEKOLAH AGAMA SERI CHOMEL","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03020": {"rujukan":"20","nama":"SEKOLAH AGAMA SERI LAKSANA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03021": {"rujukan":"21","nama":"SEKOLAH AGAMA SERI BERKAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03022": {"rujukan":"22","nama":"SEKOLAH AGAMA PADANG SARI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03023": {"rujukan":"23","nama":"SEKOLAH AGAMA KANGKAR MERLIMAU","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03024": {"rujukan":"24","nama":"SEKOLAH AGAMA MAMPAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03025": {"rujukan":"25","nama":"SEKOLAH AGAMA SERI TIGA SERANGKAI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03026": {"rujukan":"26","nama":"SEKOLAH AGAMA SERI PASIR PUTEH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03027": {"rujukan":"27","nama":"SEKOLAH AGAMA BINDU","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03028": {"rujukan":"28","nama":"SEKOLAH AGAMA SEPAKAT JAYA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03029": {"rujukan":"29","nama":"SEKOLAH AGAMA SERI MEDAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03030": {"rujukan":"30","nama":"SEKOLAH AGAMA SERI YONG PENG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03031": {"rujukan":"31","nama":"SEKOLAH AGAMA SERI SEJAGUNG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03032": {"rujukan":"32","nama":"SEKOLAH AGAMA LADANG YONG PENG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03033": {"rujukan":"33","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) BATU PAHAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03034": {"rujukan":"34","nama":"SEKOLAH AGAMA PERMATANG RENGAS","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03035": {"rujukan":"35","nama":"SEKOLAH AGAMA PT BILAL","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03036": {"rujukan":"36","nama":"SEKOLAH AGAMA SERI TENGAH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03037": {"rujukan":"37","nama":"SEKOLAH AGAMA KENANGAN DATO' ONN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03038": {"rujukan":"38","nama":"SEKOLAH AGAMA SERI TANJONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03039": {"rujukan":"39","nama":"SEKOLAH AGAMA SERI BERTAM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03040": {"rujukan":"40","nama":"SEKOLAH AGAMA SERI BINJAI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03041": {"rujukan":"41","nama":"SEKOLAH AGAMA SERI BENGKAL","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03042": {"rujukan":"42","nama":"SEKOLAH AGAMA PARIT LAPIS","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03043": {"rujukan":"43","nama":"SEKOLAH AGAMA SERI TELOK","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03044": {"rujukan":"44","nama":"SEKOLAH AGAMA SERI NASIB BAIK","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03045": {"rujukan":"45","nama":"SEKOLAH AGAMA SERI DAYUNG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03046": {"rujukan":"46","nama":"SEKOLAH AGAMA TENAGA SEPAKAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03047": {"rujukan":"47","nama":"SEKOLAH AGAMA BUKIT RAHMAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03048": {"rujukan":"48","nama":"SEKOLAH AGAMA SERI PASIR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03049": {"rujukan":"49","nama":"SEKOLAH AGAMA BUKIT PASIR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03050": {"rujukan":"50","nama":"SEKOLAH AGAMA SRI IDAMAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03051": {"rujukan":"51","nama":"SEKOLAH AGAMA SERI SEJATI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03052": {"rujukan":"52","nama":"SEKOLAH AGAMA TENAGA SETIA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03053": {"rujukan":"53","nama":"SEKOLAH AGAMA SERI MANGGIS","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03054": {"rujukan":"54","nama":"SEKOLAH AGAMA SENGKUANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03055": {"rujukan":"55","nama":"SEKOLAH AGAMA TANJUNG SEMBERONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03056": {"rujukan":"56","nama":"SEKOLAH AGAMA SERI MENDAPAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03057": {"rujukan":"57","nama":"SEKOLAH AGAMA SERI GADING","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03058": {"rujukan":"58","nama":"SEKOLAH AGAMA SERI BEROLEH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03059": {"rujukan":"59","nama":"SEKOLAH AGAMA SERI BUNUT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03060": {"rujukan":"60","nama":"SEKOLAH AGAMA PINTAS PUDING","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03061": {"rujukan":"61","nama":"SEKOLAH AGAMA SERI BULAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03062": {"rujukan":"62","nama":"SEKOLAH AGAMA PARIT BINGAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03063": {"rujukan":"63","nama":"SEKOLAH AGAMA SETIA JAYA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03064": {"rujukan":"64","nama":"SEKOLAH AGAMA KAMPUNG ISTANA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03065": {"rujukan":"65","nama":"SEKOLAH AGAMA PARIT RAJA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03066": {"rujukan":"66","nama":"SEKOLAH AGAMA SERI PANDAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03067": {"rujukan":"67","nama":"SEKOLAH AGAMA JELUTONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03068": {"rujukan":"68","nama":"SEKOLAH AGAMA BATU 18 AIR HITAM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03069": {"rujukan":"69","nama":"SEKOLAH AGAMA SERI AMAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03070": {"rujukan":"70","nama":"SEKOLAH AGAMA SERI BANDAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03071": {"rujukan":"71","nama":"SEKOLAH AGAMA SERI PAYA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03072": {"rujukan":"72","nama":"SEKOLAH AGAMA BUKIT KUARI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03073": {"rujukan":"73","nama":"SEKOLAH AGAMA SERI SABAK UNI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03074": {"rujukan":"74","nama":"SEKOLAH AGAMA SERI KEMAJUAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03075": {"rujukan":"75","nama":"SEKOLAH AGAMA PINTAS RAYA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03076": {"rujukan":"76","nama":"SEKOLAH AGAMA PARIT SEMO","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03077": {"rujukan":"77","nama":"SEKOLAH AGAMA AYER HITAM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03078": {"rujukan":"78","nama":"SEKOLAH AGAMA SERI BELAHAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03079": {"rujukan":"79","nama":"SEKOLAH AGAMA SERI LADANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03080": {"rujukan":"80","nama":"SEKOLAH AGAMA SERI MERLONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03081": {"rujukan":"81","nama":"SEKOLAH AGAMA SERI PERPAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03082": {"rujukan":"82","nama":"SEKOLAH AGAMA PARIT KEMANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03083": {"rujukan":"83","nama":"SEKOLAH AGAMA MERLONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03084": {"rujukan":"84","nama":"SEKOLAH AGAMA SERI PULEH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03085": {"rujukan":"85","nama":"SEKOLAH AGAMA SUNGAI TONGKANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03086": {"rujukan":"86","nama":"SEKOLAH AGAMA SERI TIMBUL","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03087": {"rujukan":"87","nama":"SEKOLAH AGAMA PARIT GANTONG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03088": {"rujukan":"88","nama":"SEKOLAH AGAMA RENGIT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03089": {"rujukan":"89","nama":"SEKOLAH AGAMA SERI BAHAGIA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03090": {"rujukan":"90","nama":"SEKOLAH AGAMA MINYAK BEKU","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03091": {"rujukan":"91","nama":"SEKOLAH AGAMA BANDAR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03092": {"rujukan":"92","nama":"SEKOLAH AGAMA KORIS","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03093": {"rujukan":"93","nama":"SEKOLAH AGAMA SERI MOLEK","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03094": {"rujukan":"94","nama":"SEKOLAH AGAMA SERI MULIA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03095": {"rujukan":"95","nama":"SEKOLAH AGAMA PENGGARAM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03096": {"rujukan":"96","nama":"SEKOLAH AGAMA SENGGARANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03097": {"rujukan":"97","nama":"SEKOLAH AGAMA SUNGAI SULOH","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03098": {"rujukan":"98","nama":"SEKOLAH AGAMA SERI REJO SARI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03099": {"rujukan":"99","nama":"SEKOLAH AGAMA KAMPUNG BAHARU","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03100": {"rujukan":"100","nama":"SEKOLAH AGAMA PUNGGUR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03101": {"rujukan":"101","nama":"SEKOLAH AGAMA PARIT KADIR","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03102": {"rujukan":"102","nama":"SEKOLAH AGAMA SERI BANANG","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03104": {"rujukan":"103","nama":"SEKOLAH AGAMA BANANG JAYA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03105": {"rujukan":"104","nama":"SEKOLAH AGAMA TAMAN KOTA, BATU PAHAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03106": {"rujukan":"105","nama":"SEKOLAH AGAMA TAMAN BUKIT PERDANA, BATU PAHAT","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03107": {"rujukan":"106","nama":"SEKOLAH RENDAH ISLAM AT TAHFIZ PARIT RAJA","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03108": {"rujukan":"107","nama":"SEKOLAH RENDAH TAHFIZ INTEGRASI ISMAIL KAMARI (SERTIK)","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03109": {"rujukan":"108","nama":"SEKOLAH RENDAH ISLAM RIYADUS SOLIHIN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03110": {"rujukan":"109","nama":"MADRASAH TARBIYAH AD DARUNNAFIS","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03111": {"rujukan":"110","nama":"MADRASAH TAHFIZ AL QURAN JAWAHER AL ULUM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03112": {"rujukan":"111","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM TAHFIZ AL-IKHSAN","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03113": {"rujukan":"112","nama":"SEKOLAH RENDAH ISLAM HIDAYAH (BATU PAHAT)","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03114": {"rujukan":"113","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL-HAKIM","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03115": {"rujukan":"114","nama":"MAAHAD TAHFIZ AL MAARIF","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03116": {"rujukan":"115","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL-AZHAR, SRI GADING","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03117": {"rujukan":"116","nama":"MAAHAD INTEGRASI TAHFIZ AL-FATHI","negeri":"JOHOR","daerah":"BATU PAHAT"},
"J03118": {"rujukan":"117","nama":"SEKOLAH RENDAH ISLAM BESTARI AL-MUHSININ","negeri":"JOHOR","daerah":"BATU PAHAT"},
"SIMPANAN-BATU-PAHAT": {"rujukan":"118","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"BATU PAHAT"}, 
"J04001": {"rujukan":"1","nama":"SEKOLAH AGAMA LABIS","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04002": {"rujukan":"2","nama":"SEKOLAH AGAMA FELDA TENANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04003": {"rujukan":"3","nama":"SEKOLAH AGAMA ISMAIL ARIFFIN, PEKAN AIR PANAS","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04004": {"rujukan":"4","nama":"SEKOLAH AGAMA FELDA CHEMPLAK","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04005": {"rujukan":"5","nama":"SEKOLAH AGAMA CHAAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04006": {"rujukan":"6","nama":"SEKOLAH AGAMA FELDA KEMELAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04007": {"rujukan":"7","nama":"SEKOLAH AGAMA FELDA CHEMPLAK BARAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04008": {"rujukan":"8","nama":"SEKOLAH AGAMA FELDA REDONG 01","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04009": {"rujukan":"9","nama":"SEKOLAH AGAMA TENANG STESEN","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04010": {"rujukan":"10","nama":"SEKOLAH AGAMA DESA TEMU JODOH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04011": {"rujukan":"11","nama":"SEKOLAH AGAMA FELDA MAOKIL 1","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04012": {"rujukan":"12","nama":"SEKOLAH AGAMA FELDA MAOKIL 2","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04013": {"rujukan":"13","nama":"SEKOLAH AGAMA BEKOK","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04014": {"rujukan":"14","nama":"SEKOLAH AGAMA KAMPUNG TENANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04015": {"rujukan":"15","nama":"SEKOLAH AGAMA PERUMAHAN AWAM","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04016": {"rujukan":"16","nama":"SEKOLAH AGAMA SAWAH BARU","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04017": {"rujukan":"17","nama":"SEKOLAH AGAMA MELAYU RAYA, SEGAMAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04018": {"rujukan":"18","nama":"SEKOLAH AGAMA KAMPUNG TENGAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04019": {"rujukan":"19","nama":"SEKOLAH AGAMA BANDAR SEGAMAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04020": {"rujukan":"20","nama":"SEKOLAH AGAMA MUKIM JABI","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04021": {"rujukan":"21","nama":"SEKOLAH AGAMA GEMEREH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04022": {"rujukan":"22","nama":"SEKOLAH AGAMA BUKIT TUNGGAL","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04023": {"rujukan":"23","nama":"SEKOLAH AGAMA JEMENTAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04024": {"rujukan":"24","nama":"SEKOLAH AGAMA PAYA JAKAS","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04025": {"rujukan":"25","nama":"SEKOLAH AGAMA BUKIT KELEDANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04026": {"rujukan":"26","nama":"SEKOLAH AGAMA POGOH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04027": {"rujukan":"27","nama":"SEKOLAH AGAMA KAMPUNG JAWA","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04028": {"rujukan":"28","nama":"SEKOLAH AGAMA FELDA MEDOI","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04029": {"rujukan":"29","nama":"SEKOLAH AGAMA PAYA BESAR","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04030": {"rujukan":"30","nama":"SEKOLAH AGAMA SEGAMAT BARU","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04031": {"rujukan":"31","nama":"SEKOLAH AGAMA TEBING TINGGI","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04032": {"rujukan":"32","nama":"SEKOLAH AGAMA BANDAR PUTRA,SEGAMAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04033": {"rujukan":"33","nama":"SEKOLAH AGAMA BUKIT SIPUT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04034": {"rujukan":"34","nama":"SEKOLAH AGAMA SEPINANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04035": {"rujukan":"35","nama":"SEKOLAH AGAMA BULOH KASAP","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04036": {"rujukan":"36","nama":"SEKOLAH AGAMA KUALA PAYA","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04037": {"rujukan":"37","nama":"SEKOLAH AGAMA BATU ANAM","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04038": {"rujukan":"38","nama":"SEKOLAH AGAMA AWAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04039": {"rujukan":"39","nama":"SEKOLAH AGAMA SPANG LOI","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04040": {"rujukan":"40","nama":"SEKOLAH AGAMA FELDA PEMANIS 1","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04041": {"rujukan":"41","nama":"SEKOLAH AGAMA FELDA PEMANIS 2","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04042": {"rujukan":"42","nama":"SEKOLAH AGAMA DARUL FALAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04043": {"rujukan":"43","nama":"SEKOLAH AGAMA KEMEDAK","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04044": {"rujukan":"44","nama":"SEKOLAH AGAMA HAJAH NOMAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04045": {"rujukan":"45","nama":"SEKOLAH AGAMA MENSUDUT LAMA","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04046": {"rujukan":"46","nama":"SEKOLAH AGAMA BALAI BADANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04047": {"rujukan":"47","nama":"SEKOLAH AGAMA LADANG PALONG TIMUR 4&5","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04048": {"rujukan":"48","nama":"SEKOLAH AGAMA BUKIT BUJANG","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04049": {"rujukan":"49","nama":"SEKOLAH AGAMA MENSUDUT PINDAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04050": {"rujukan":"50","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) SEGAMAT","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04051": {"rujukan":"51","nama":"SEKOLAH AGAMA GEMAS BARU","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04052": {"rujukan":"52","nama":"SEKOLAH AGAMA TAMAN PELANGI","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04053": {"rujukan":"53","nama":"SEKOLAH AGAMA TAMAN YAYASAN","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04055": {"rujukan":"54","nama":"SEKOLAH AGAMA SEGAMAT KECIL","negeri":"JOHOR","daerah":"SEGAMAT"},
"J04056": {"rujukan":"55","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL FATIH BANDAR PUTRA","negeri":"JOHOR","daerah":"SEGAMAT"},
"SIMPANAN-SEGAMAT": {"rujukan":"56","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"SEGAMAT"},
"J05001": {"rujukan":"1","nama":"SEKOLAH AGAMA FELDA BUKIT TONGKAT","negeri":"JOHOR","daerah":"KLUANG"},
"J05002": {"rujukan":"2","nama":"SEKOLAH AGAMA FELDA KAHANG BARAT","negeri":"JOHOR","daerah":"KLUANG"},
"J05003": {"rujukan":"3","nama":"SEKOLAH AGAMA FELDA KAHANG TIMUR","negeri":"JOHOR","daerah":"KLUANG"},
"J05004": {"rujukan":"4","nama":"SEKOLAH AGAMA FELDA ULU BELITONG","negeri":"JOHOR","daerah":"KLUANG"},
"J05005": {"rujukan":"5","nama":"SEKOLAH AGAMA FELDA ULU DENGAR","negeri":"JOHOR","daerah":"KLUANG"},
"J05006": {"rujukan":"6","nama":"SEKOLAH AGAMA FELDA ULU PENGGELI","negeri":"JOHOR","daerah":"KLUANG"},
"J05007": {"rujukan":"7","nama":"SEKOLAH AGAMA DATO' AHMAD","negeri":"JOHOR","daerah":"KLUANG"},
"J05008": {"rujukan":"8","nama":"SEKOLAH AGAMA KAHANG BT 28","negeri":"JOHOR","daerah":"KLUANG"},
"J05009": {"rujukan":"9","nama":"SEKOLAH AGAMA KAMPUNG CONTOH","negeri":"JOHOR","daerah":"KLUANG"},
"J05010": {"rujukan":"10","nama":"SEKOLAH AGAMA SRI KAMPUNG TENGAH 1","negeri":"JOHOR","daerah":"KLUANG"},
"J05011": {"rujukan":"11","nama":"SEKOLAH AGAMA SRI KAMPUNG TENGAH 2","negeri":"JOHOR","daerah":"KLUANG"},
"J05012": {"rujukan":"12","nama":"SEKOLAH AGAMA KLUANG BARAT","negeri":"JOHOR","daerah":"KLUANG"},
"J05013": {"rujukan":"13","nama":"SEKOLAH AGAMA LADANG MUTIARA","negeri":"JOHOR","daerah":"KLUANG"},
"J05014": {"rujukan":"14","nama":"SEKOLAH AGAMA LADANG PAMOL","negeri":"JOHOR","daerah":"KLUANG"},
"J05015": {"rujukan":"15","nama":"SEKOLAH AGAMA SULTAN SIR IBRAHIM","negeri":"JOHOR","daerah":"KLUANG"},
"J05016": {"rujukan":"16","nama":"SEKOLAH AGAMA TAMAN SRI LAMBAK","negeri":"JOHOR","daerah":"KLUANG"},
"J05017": {"rujukan":"17","nama":"SEKOLAH AGAMA SRI LALANG","negeri":"JOHOR","daerah":"KLUANG"},
"J05018": {"rujukan":"18","nama":"SEKOLAH AGAMA FELDA AYER HITAM","negeri":"JOHOR","daerah":"KLUANG"},
"J05019": {"rujukan":"19","nama":"SEKOLAH AGAMA BANDAR KLUANG","negeri":"JOHOR","daerah":"KLUANG"},
"J05020": {"rujukan":"20","nama":"SEKOLAH AGAMA BANDAR PALOH 1","negeri":"JOHOR","daerah":"KLUANG"},
"J05021": {"rujukan":"21","nama":"SEKOLAH AGAMA BANDAR PALOH 2","negeri":"JOHOR","daerah":"KLUANG"},
"J05022": {"rujukan":"22","nama":"SEKOLAH AGAMA GUNUNG LAMBAK","negeri":"JOHOR","daerah":"KLUANG"},
"J05023": {"rujukan":"23","nama":"SEKOLAH AGAMA KEM MAHKOTA","negeri":"JOHOR","daerah":"KLUANG"},
"J05024": {"rujukan":"24","nama":"SEKOLAH AGAMA KAMPUNG MELAYU CHAMEK","negeri":"JOHOR","daerah":"KLUANG"},
"J05025": {"rujukan":"25","nama":"SEKOLAH AGAMA LADANG BUKIT BENUT","negeri":"JOHOR","daerah":"KLUANG"},
"J05026": {"rujukan":"26","nama":"SEKOLAH AGAMA LADANG BUKIT PALOH","negeri":"JOHOR","daerah":"KLUANG"},
"J05027": {"rujukan":"27","nama":"SEKOLAH AGAMA LADANG TEREH","negeri":"JOHOR","daerah":"KLUANG"},
"J05028": {"rujukan":"28","nama":"SEKOLAH AGAMA NIYOR","negeri":"JOHOR","daerah":"KLUANG"},
"J05029": {"rujukan":"29","nama":"SEKOLAH AGAMA TAMAN DELIMA","negeri":"JOHOR","daerah":"KLUANG"},
"J05030": {"rujukan":"30","nama":"SEKOLAH AGAMA SERI TAMAN KLUANG BARAT","negeri":"JOHOR","daerah":"KLUANG"},
"J05031": {"rujukan":"31","nama":"SEKOLAH AGAMA TAMAN DESA","negeri":"JOHOR","daerah":"KLUANG"},
"J05032": {"rujukan":"32","nama":"SEKOLAH AGAMA BANDAR RENGAM","negeri":"JOHOR","daerah":"KLUANG"},
"J05033": {"rujukan":"33","nama":"SEKOLAH AGAMA BUKIT KENANGAN","negeri":"JOHOR","daerah":"KLUANG"},
"J05034": {"rujukan":"34","nama":"SEKOLAH AGAMA DATO' IBRAHIM MAJID","negeri":"JOHOR","daerah":"KLUANG"},
"J05035": {"rujukan":"35","nama":"SEKOLAH AGAMA FELDA LAYANG-LAYANG","negeri":"JOHOR","daerah":"KLUANG"},
"J05036": {"rujukan":"36","nama":"SEKOLAH AGAMA KOMPLEKS PENGHULU","negeri":"JOHOR","daerah":"KLUANG"},
"J05037": {"rujukan":"37","nama":"SEKOLAH AGAMA LADANG ULU REMIS","negeri":"JOHOR","daerah":"KLUANG"},
"J05038": {"rujukan":"38","nama":"SEKOLAH AGAMA PEKAN LAYANG-LAYANG","negeri":"JOHOR","daerah":"KLUANG"},
"J05039": {"rujukan":"39","nama":"SEKOLAH AGAMA PENJARA SIMPANG RENGGAM","negeri":"JOHOR","daerah":"KLUANG"},
"J05040": {"rujukan":"40","nama":"SEKOLAH AGAMA PASUKAN GERAKAN AM","negeri":"JOHOR","daerah":"KLUANG"},
"J05041": {"rujukan":"41","nama":"SEKOLAH AGAMA PT HJ HASHIM","negeri":"JOHOR","daerah":"KLUANG"},
"J05042": {"rujukan":"42","nama":"SEKOLAH AGAMA SIMPANG RENGGAM","negeri":"JOHOR","daerah":"KLUANG"},
"J05043": {"rujukan":"43","nama":"SEKOLAH AGAMA SERI KENCANA","negeri":"JOHOR","daerah":"KLUANG"},
"J05044": {"rujukan":"44","nama":"SEKOLAH AGAMA SRI MACAP","negeri":"JOHOR","daerah":"KLUANG"},
"J05045": {"rujukan":"45","nama":"SEKOLAH AGAMA SRI MAJU JAYA","negeri":"JOHOR","daerah":"KLUANG"},
"J05046": {"rujukan":"46","nama":"SEKOLAH AGAMA SRI TENGAH RENGGAM","negeri":"JOHOR","daerah":"KLUANG"},
"J05047": {"rujukan":"47","nama":"SEKOLAH AGAMA SUNGAI LINAU","negeri":"JOHOR","daerah":"KLUANG"},
"J05048": {"rujukan":"48","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) KLUANG","negeri":"JOHOR","daerah":"KLUANG"},
"J05049": {"rujukan":"49","nama":"SEKOLAH RENDAH ISLAM AS-SYDDIQ","negeri":"JOHOR","daerah":"KLUANG"},
"J05051": {"rujukan":"50","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL UKHUWWAH KLUANG","negeri":"JOHOR","daerah":"KLUANG"},
"SIMPANAN-KLUANG": {"rujukan":"51","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"KLUANG"},
"J06001": {"rujukan":"1","nama":"SEKOLAH AGAMA PULAI SEBATANG","negeri":"JOHOR","daerah":"PONTIAN"},
"J06002": {"rujukan":"2","nama":"SEKOLAH AGAMA KAMPUNG JAWA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06003": {"rujukan":"3","nama":"SEKOLAH AGAMA LEBAI MOHD YA'KOB","negeri":"JOHOR","daerah":"PONTIAN"},
"J06004": {"rujukan":"4","nama":"SEKOLAH AGAMA SERI PULAI","negeri":"JOHOR","daerah":"PONTIAN"},
"J06005": {"rujukan":"5","nama":"SEKOLAH AGAMA SERI ANOM","negeri":"JOHOR","daerah":"PONTIAN"},
"J06006": {"rujukan":"6","nama":"SEKOLAH AGAMA JAYA MULIA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06007": {"rujukan":"7","nama":"SEKOLAH AGAMA SERI SEKAWAN DESA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06008": {"rujukan":"8","nama":"SEKOLAH AGAMA SANGLANG","negeri":"JOHOR","daerah":"PONTIAN"},
"J06009": {"rujukan":"9","nama":"SEKOLAH AGAMA SERI AL-ULUM","negeri":"JOHOR","daerah":"PONTIAN"},
"J06010": {"rujukan":"10","nama":"SEKOLAH AGAMA SERI SENANG HATI","negeri":"JOHOR","daerah":"PONTIAN"},
"J06011": {"rujukan":"11","nama":"SEKOLAH AGAMA BANDAR BENUT","negeri":"JOHOR","daerah":"PONTIAN"},
"J06012": {"rujukan":"12","nama":"SEKOLAH AGAMA SERI KEMBAR","negeri":"JOHOR","daerah":"PONTIAN"},
"J06013": {"rujukan":"13","nama":"SEKOLAH AGAMA SERI SEMANGAT","negeri":"JOHOR","daerah":"PONTIAN"},
"J06014": {"rujukan":"14","nama":"SEKOLAH AGAMA PERMATANG DUKU","negeri":"JOHOR","daerah":"PONTIAN"},
"J06015": {"rujukan":"15","nama":"SEKOLAH AGAMA PERMATANG SEPAM","negeri":"JOHOR","daerah":"PONTIAN"},
"J06016": {"rujukan":"16","nama":"SEKOLAH AGAMA SERI BAHAGIA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06017": {"rujukan":"17","nama":"SEKOLAH AGAMA AL-MUSTAFA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06018": {"rujukan":"18","nama":"SEKOLAH AGAMA SERI BUGIS","negeri":"JOHOR","daerah":"PONTIAN"},
"J06019": {"rujukan":"19","nama":"SEKOLAH AGAMA PARIT MARKOM","negeri":"JOHOR","daerah":"PONTIAN"},
"J06020": {"rujukan":"20","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) PONTIAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06021": {"rujukan":"21","nama":"SEKOLAH AGAMA BANDAR PONTIAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06022": {"rujukan":"22","nama":"SEKOLAH AGAMA PARIT SEMERAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06023": {"rujukan":"23","nama":"SEKOLAH AGAMA PARIT PATAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06024": {"rujukan":"24","nama":"SEKOLAH AGAMA SERI BUKIT PANJANG","negeri":"JOHOR","daerah":"PONTIAN"},
"J06025": {"rujukan":"25","nama":"SEKOLAH AGAMA PARIT SELANGOR","negeri":"JOHOR","daerah":"PONTIAN"},
"J06026": {"rujukan":"26","nama":"SEKOLAH AGAMA PARIT HAJI ADNAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06027": {"rujukan":"27","nama":"SEKOLAH AGAMA MELAYU RAYA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06028": {"rujukan":"28","nama":"SEKOLAH AGAMA KAMPUNG SAWAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06029": {"rujukan":"29","nama":"SEKOLAH AGAMA PEKAN NANAS","negeri":"JOHOR","daerah":"PONTIAN"},
"J06030": {"rujukan":"30","nama":"SEKOLAH AGAMA JERAM BATU","negeri":"JOHOR","daerah":"PONTIAN"},
"J06031": {"rujukan":"31","nama":"SEKOLAH AGAMA API-API","negeri":"JOHOR","daerah":"PONTIAN"},
"J06032": {"rujukan":"32","nama":"SEKOLAH AGAMA PONTIAN BESAR","negeri":"JOHOR","daerah":"PONTIAN"},
"J06033": {"rujukan":"33","nama":"SEKOLAH AGAMA PARIT KUDUS","negeri":"JOHOR","daerah":"PONTIAN"},
"J06034": {"rujukan":"34","nama":"SEKOLAH AGAMA KAYU ARA PASONG","negeri":"JOHOR","daerah":"PONTIAN"},
"J06035": {"rujukan":"35","nama":"SEKOLAH AGAMA PARIT SAPRAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06036": {"rujukan":"36","nama":"SEKOLAH AGAMA TANJUNG AYER HITAM","negeri":"JOHOR","daerah":"PONTIAN"},
"J06037": {"rujukan":"37","nama":"SEKOLAH AGAMA BATU 24","negeri":"JOHOR","daerah":"PONTIAN"},
"J06038": {"rujukan":"38","nama":"SEKOLAH AGAMA BANDAR PERMAS","negeri":"JOHOR","daerah":"PONTIAN"},
"J06039": {"rujukan":"39","nama":"SEKOLAH AGAMA SERKAT","negeri":"JOHOR","daerah":"PONTIAN"},
"J06040": {"rujukan":"40","nama":"SEKOLAH AGAMA TELOK KERANG","negeri":"JOHOR","daerah":"PONTIAN"},
"J06041": {"rujukan":"41","nama":"SEKOLAH AGAMA RIMBA TERJUN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06042": {"rujukan":"42","nama":"SEKOLAH AGAMA SERI BUNIAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06043": {"rujukan":"43","nama":"SEKOLAH AGAMA RAMBAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06044": {"rujukan":"44","nama":"SEKOLAH AGAMA PENEROK","negeri":"JOHOR","daerah":"PONTIAN"},
"J06045": {"rujukan":"45","nama":"SEKOLAH AGAMA PENGKALAN RAJA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06046": {"rujukan":"46","nama":"SEKOLAH AGAMA SUNGAI BOH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06047": {"rujukan":"47","nama":"SEKOLAH AGAMA KAMPUNG BARU","negeri":"JOHOR","daerah":"PONTIAN"},
"J06048": {"rujukan":"48","nama":"SEKOLAH AGAMA SUNGAI BUNYI","negeri":"JOHOR","daerah":"PONTIAN"},
"J06049": {"rujukan":"49","nama":"SEKOLAH AGAMA AS-SYARIF PARIT RAMBAI","negeri":"JOHOR","daerah":"PONTIAN"},
"J06050": {"rujukan":"50","nama":"SEKOLAH AGAMA TENGGAYUN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06051": {"rujukan":"51","nama":"SEKOLAH AGAMA BELOKOK","negeri":"JOHOR","daerah":"PONTIAN"},
"J06052": {"rujukan":"52","nama":"SEKOLAH AGAMA SERI SINARAN CHOKOH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06053": {"rujukan":"53","nama":"SEKOLAH AGAMA PARIT SULAIMAN","negeri":"JOHOR","daerah":"PONTIAN"},
"J06054": {"rujukan":"54","nama":"SEKOLAH AGAMA PERMAS KELAPA","negeri":"JOHOR","daerah":"PONTIAN"},
"J06055": {"rujukan":"55","nama":"MADRASAH TAHFIZ DARUL FALAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J06056": {"rujukan":"56","nama":"SEKOLAH RENDAH ISLAM (SRITI) AL-JAUHAR, PONTIAN","negeri":"JOHOR","daerah":"PONTIAN"},
"SIMPANAN-PONTIAN": {"rujukan":"57","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"PONTIAN"},
"J07048": {"rujukan":"1","nama":"SEKOLAH AGAMA BANDAR KOTA TINGGI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07016": {"rujukan":"2","nama":"SEKOLAH AGAMA SUNGAI TELOR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07018": {"rujukan":"3","nama":"SEKOLAH AGAMA LADANG YPJ","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07013": {"rujukan":"4","nama":"SEKOLAH AGAMA FELDA PASIR RAJA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07012": {"rujukan":"5","nama":"SEKOLAH AGAMA FELDA BUKIT BESAR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07014": {"rujukan":"6","nama":"SEKOLAH AGAMA FELDA BUKIT RAMUN","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07011": {"rujukan":"7","nama":"SEKOLAH AGAMA FELDA SUNGAI SAYONG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07007": {"rujukan":"8","nama":"SEKOLAH AGAMA FELDA PENGELI TIMUR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07009": {"rujukan":"9","nama":"SEKOLAH AGAMA FELDA SUNGAI SIBOL","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07004": {"rujukan":"10","nama":"SEKOLAH AGAMA BANDAR TENGGARA 1","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07008": {"rujukan":"11","nama":"SEKOLAH AGAMA FELDA LINGGIU","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07010": {"rujukan":"12","nama":"SEKOLAH AGAMA PETRI JAYA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07020": {"rujukan":"13","nama":"SEKOLAH AGAMA SEMANGAR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07002": {"rujukan":"14","nama":"SEKOLAH AGAMA BUKIT LINTANG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07003": {"rujukan":"15","nama":"SEKOLAH AGAMA TAMAN SAYONG PINANG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07001": {"rujukan":"16","nama":"SEKOLAH AGAMA TAMAN KOTA JAYA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07017": {"rujukan":"17","nama":"SEKOLAH AGAMA LADANG ALAF Y.P.J","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07031": {"rujukan":"18","nama":"SEKOLAH AGAMA BANDAR SRI PERANI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07030": {"rujukan":"19","nama":"SEKOLAH AGAMA MAWAI BARU","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07023": {"rujukan":"20","nama":"SEKOLAH AGAMA AL FALAH FELDA BUKIT APING BARAT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07024": {"rujukan":"21","nama":"SEKOLAH AGAMA FELDA BUKIT APING TIMUR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07035": {"rujukan":"22","nama":"SEKOLAH AGAMA AL ANSAR FELDA LOK HENG SELATAN","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07021": {"rujukan":"23","nama":"SEKOLAH AGAMA AS-SYAKIRIN FELDA GUGUSAN WAHA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07022": {"rujukan":"24","nama":"SEKOLAH AGAMA DARUL ULUM FELDA SIMPANG WAHA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07027": {"rujukan":"25","nama":"SEKOLAH AGAMA KAMPUNG GEMBUT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07026": {"rujukan":"26","nama":"SEKOLAH AGAMA SRI MAHKOTA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07069": {"rujukan":"27","nama":"SEKOLAH AGAMA TELOK HUTAN LESONG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07029": {"rujukan":"28","nama":"SEKOLAH AGAMA SEDILI KECIL","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07028": {"rujukan":"29","nama":"SEKOLAH AGAMA SEDILI BESAR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07032": {"rujukan":"30","nama":"SEKOLAH AGAMA FELDA TENGGAROH SELATAN","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07025": {"rujukan":"31","nama":"SEKOLAH AGAMA FELCRA SUNGAI ARA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07064": {"rujukan":"32","nama":"SEKOLAH AGAMA TUNJUK LAUT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07049": {"rujukan":"33","nama":"SEKOLAH AGAMA FELDA PASAK","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07050": {"rujukan":"34","nama":"SEKOLAH AGAMA FELDA AIR TAWAR 1","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07051": {"rujukan":"35","nama":"SEKOLAH AGAMA FELDA AIR TAWAR 2","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07052": {"rujukan":"36","nama":"SEKOLAH AGAMA FELDA AIR TAWAR 3","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07053": {"rujukan":"37","nama":"SEKOLAH AGAMA FELDA AIR TAWAR 4","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07054": {"rujukan":"38","nama":"SEKOLAH AGAMA FELDA AIR TAWAR 5","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07055": {"rujukan":"39","nama":"SEKOLAH AGAMA FELDA SEMENCHU","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07057": {"rujukan":"40","nama":"SEKOLAH AGAMA FELDA PAPAN TIMUR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07056": {"rujukan":"41","nama":"SEKOLAH AGAMA BANDAR MAS","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07058": {"rujukan":"42","nama":"SEKOLAH AGAMA TELOK SENGAT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07019": {"rujukan":"43","nama":"SEKOLAH AGAMA LADANG NAM HENG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07061": {"rujukan":"44","nama":"SEKOLAH AGAMA KAMPUNG PANCHOR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07059": {"rujukan":"45","nama":"SEKOLAH AGAMA SUNGAI LAYAU","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07068": {"rujukan":"46","nama":"SEKOLAH AGAMA TANJUNG BUAI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07063": {"rujukan":"47","nama":"SEKOLAH AGAMA JOHOR KAMPUNG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07034": {"rujukan":"48","nama":"SEKOLAH AGAMA NURUL FALAH GUGUSAN FELDA LOK HENG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07036": {"rujukan":"49","nama":"SEKOLAH AGAMA FELDA SUNGAI MAS","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07033": {"rujukan":"50","nama":"SEKOLAH AGAMA BANDAR PENAWAR","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07039": {"rujukan":"51","nama":"SEKOLAH AGAMA FELDA SENING","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07040": {"rujukan":"52","nama":"SEKOLAH AGAMA FELDA ADELA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07038": {"rujukan":"53","nama":"SEKOLAH AGAMA FELDA KLEDANG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07037": {"rujukan":"54","nama":"SEKOLAH AGAMA FELDA TUNGGAL","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07045": {"rujukan":"55","nama":"SEKOLAH AGAMA PASIR GOGOK","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07046": {"rujukan":"56","nama":"SEKOLAH AGAMA TANJUNG SERINDIT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07073": {"rujukan":"57","nama":"SEKOLAH AGAMA TANJUNG SURAT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07043": {"rujukan":"58","nama":"SEKOLAH AGAMA TELUK RAMUNIA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07047": {"rujukan":"59","nama":"SEKOLAH AGAMA PUNGGAI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07044": {"rujukan":"60","nama":"SEKOLAH AGAMA SUNGAI RENGIT","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07042": {"rujukan":"61","nama":"SEKOLAH AGAMA PENGERANG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07066": {"rujukan":"62","nama":"SEKOLAH AGAMA LEPAU","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07060": {"rujukan":"63","nama":"SEKOLAH AGAMA TAMAN SRI SAUJANA 1","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07062": {"rujukan":"64","nama":"SEKOLAH AGAMA DATUK USMAN AWANG","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07006": {"rujukan":"65","nama":"SEKOLAH AGAMA TUAN SEH","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07070": {"rujukan":"66","nama":"SEKOLAH AGAMA TAMAN PASAK INDAH","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07071": {"rujukan":"67","nama":"SEKOLAH AGAMA TAMAN ANGGERIK TENGGARA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07072": {"rujukan":"68","nama":"SEKOLAH AGAMA KOTA KECHIL","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07041": {"rujukan":"69","nama":"SEKOLAH AGAMA TAMAN BAYU DAMAI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07015": {"rujukan":"70","nama":"SEKOLAH RENDAH AGAMA BERSEPADU (SRAB) KOTA TINGGI","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"J07005": {"rujukan":"71","nama":"SEKOLAH AGAMA DESA PULADA","negeri":"JOHOR","daerah":"KOTA TINGGI"},
"SIMPANAN-KOTA-TINGGI": {"rujukan":"72","nama":"SIMPANAN DAERAH","negeri":"JOHOR","daerah":"KOTA TINGGI"},
  
"PERLIS": {"rujukan":"1","nama":"SIMPANAN NEGERI","negeri":"PERLIS","daerah":""},
"KEDAH": {"rujukan":"2","nama":"SIMPANAN NEGERI","negeri":"KEDAH","daerah":""},
"PULAU PINANG": {"rujukan":"3","nama":"SIMPANAN NEGERI","negeri":"PULAU PINANG","daerah":""},
"PERAK": {"rujukan":"4","nama":"SIMPANAN NEGERI","negeri":"PERAK","daerah":""},
"SELANGOR": {"rujukan":"5","nama":"SIMPANAN NEGERI","negeri":"SELANGOR","daerah":""},
"WILAYAH PERSEKUTUAN": {"rujukan":"6","nama":"SIMPANAN NEGERI","negeri":"WILAYAH PERSEKUTUAN","daerah":""},
"PUTRAJAYA": {"rujukan":"7","nama":"SIMPANAN NEGERI","negeri":"PUTRAJAYA","daerah":""},
"LABUAN": {"rujukan":"8","nama":"SIMPANAN NEGERI","negeri":"LABUAN","daerah":""},
"NEGERI SEMBILAN": {"rujukan":"9","nama":"SIMPANAN NEGERI","negeri":"NEGERI SEMBILAN","daerah":""},
"MELAKA": {"rujukan":"10","nama":"SIMPANAN NEGERI","negeri":"MELAKA","daerah":""},
"JOHOR": {"rujukan":"11","nama":"SIMPANAN NEGERI","negeri":"JOHOR","daerah":""},
"PAHANG": {"rujukan":"12","nama":"SIMPANAN NEGERI","negeri":"PAHANG","daerah":""},
"TERENGGANU": {"rujukan":"13","nama":"SIMPANAN NEGERI","negeri":"TERENGGANU","daerah":""},
"KELANTAN": {"rujukan":"14","nama":"SIMPANAN NEGERI","negeri":"KELANTAN","daerah":""},
"SABAH": {"rujukan":"15","nama":"SIMPANAN NEGERI","negeri":"SABAH","daerah":""},
"SARAWAK": {"rujukan":"16","nama":"SIMPANAN NEGERI","negeri":"SARAWAK","daerah":""},
"JAKIM": {"rujukan":"17","nama":"SIMPANAN PENGARAH BAHAGIAN PENDIDIKAN JAKIM","negeri":"JAKIM","daerah":""},
  
};
