Object.assign(window.SCHOOLS, {
"XBA5043/S01003": {"rujukan":"1","nama":"KAFA KG. MALIYU BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5035/S01016": {"rujukan":"2","nama":"KAFA KG. DAMARAN BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5022/S01005": {"rujukan":"3","nama":"KAFA KG. BATU PUTIH BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5024/S01007": {"rujukan":"4","nama":"KAFA KG. KOBONG LAUT BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5025/S01008": {"rujukan":"5","nama":"KAFA KG. LOK TUHOG BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5027/S01009": {"rujukan":"6","nama":"KAFA AGROPOLITAN BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5028/S01010": {"rujukan":"7","nama":"KAFA KG. BATU LAYAR BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5042/S01019": {"rujukan":"8","nama":"KAFA KG. LUMAIS BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5031/S01012": {"rujukan":"9","nama":"KAFA KG. LIMBUAK LAUT BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5032/S01013": {"rujukan":"10","nama":"KAFA KG. TIMBANG DAYANG BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5034/S01015": {"rujukan":"11","nama":"KAFA KG. LAKSIAN BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"XYT5037/S01017": {"rujukan":"12","nama":"KAFA KG. TANJUNG MANAWALI BANGGI","negeri":"SABAH","daerah":"BANGGI"},
"SIMPANAN-BANGGI": {"rujukan":"13","nama":"SIMPANAN DAERAH","negeri":"SABAH","daerah":"BANGGI"},

  "Q03001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN (A) MIS SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN ABANG AING SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03004": {"rujukan":"4","nama":"SJK CHUNG HUA SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN TEMUDOK KEM","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KEM PAKIT","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BAKONG SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN GRAN/STUMBIN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN TANJUNG BIJAT","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN LELA PAHLAWAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN PULAU SEDUKU","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN MELUGU","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN ENGKILILI NO. 1","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN ST LUKE","negeri":"SARAWAK","daerah":"SRI AMAN"},
"SIMPANAN-SRI-AMAN": {"rujukan":"15","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SRI AMAN"},
  "Q01001 ": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN SEMATAN","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01002 ": {"rujukan":"2","nama":"SJK CHUNG HUA SEMATAN","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01003 ": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SEBAT","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01004 ": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN PUEH","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01005 ": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN SERAYAN/KERANJI","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01006 ": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BUMIPUTERA","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01007 ": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN STUNGGANG MELAYU","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01008 ": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN LEBAI MENTALI","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01009 ": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN SIAR CAMPURAN","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01010 ": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN PUGU","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01011 ": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN SAMPADI","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01012 ": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN RAMBUNGAN","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01013 ": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN STOH","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01084 ": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN JANGKAR","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01091 ": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN TELOK MELANO","negeri":"SARAWAK","daerah":"LUNDU"},
"Q01095 ": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN SEBAKO","negeri":"SARAWAK","daerah":"LUNDU"},
"SIMPANAN-LUNDU": {"rujukan":"17","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"LUNDU"},
"Q02001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN (A) IBNU KHALDUN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN KAMPUNG BARU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN TAMBAY","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN REBAK","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN JEMUKAN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN ST MARTIN MERDANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN WIRA JAYA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN HJ BUJANG SEBANGAN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN TUANKU BAGUS SEBUYAU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN TUNGKAH MELAYU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN PENDAM","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN SERPAN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN TANJUNG APONG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN DATO' TRAOH","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN DATO MOHD MUSA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN NIUP","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SAGENG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN JAIE","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN HAJI KELALI SEMERA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN TERASI","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN ASAJAYA ULU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN SAMBIR","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN ENDAP","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN JALAN MUARA TUANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN SERUYUK","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN PINANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN ABANG MAN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN SG LADONG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN SEBANDI MATANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN SEBUYAU ENGSENGEI","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN EMPILA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN ASAJAYA LAUT","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN BELIONG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN KAMPUNG MELAYU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN SEGALI","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN HAJI BUJANG RANGAWAN PUTIN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN SEBANDI ULU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02038": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN MATA PARANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN ABANG KADIR GEDONG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN MERANEK","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN TANJUNG TUANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02042": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN SG APIN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN LUBOK BUNTIN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02044": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN IBOI/PELANDUK","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02045": {"rujukan":"45","nama":"SEKOLAH KEBANGSAAN MOYAN LAUT","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02046": {"rujukan":"46","nama":"SEKOLAH KEBANGSAAN TAMBIRAT","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02047": {"rujukan":"47","nama":"SEKOLAH KEBANGSAAN MANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02048": {"rujukan":"48","nama":"SEKOLAH KEBANGSAAN TEBELU","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02049": {"rujukan":"49","nama":"SEKOLAH KEBANGSAAN TANJUNG PISANG SELANGKING","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02050": {"rujukan":"50","nama":"SEKOLAH KEBANGSAAN SAMALATONG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02051": {"rujukan":"51","nama":"SEKOLAH KEBANGSAAN GUMPEY","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02052": {"rujukan":"52","nama":"SEKOLAH KEBANGSAAN SUNGAI BA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02054": {"rujukan":"53","nama":"SEKOLAH KEBANGSAAN LUBUK PUNGGOR","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02055": {"rujukan":"54","nama":"SEKOLAH JENIS KEBANGSAAN CHUNG HUA TAMBIRAT","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02056": {"rujukan":"55","nama":"SEKOLAH KEBANGSAAN PADANG PEDALAI","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02057": {"rujukan":"56","nama":"SEKOLAH JENIS KEBANGSAAN CHUNG HUA SEMERA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02058": {"rujukan":"57","nama":"SEKOLAH KEBANGSAAN MUNGGU LALANG","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02059": {"rujukan":"58","nama":"SEKOLAH JENIS KEBANGSAAN CHUNG HUA ASAJAYA","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q02060": {"rujukan":"59","nama":"SEKOLAH KEBANGSAAN ST MICHAEL (M) ENTINGAN","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"SIMPANAN-SAMARAHAN": {"rujukan":"60","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SAMARAHAN"},
"Q14001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN PLAMAN BAKI MENAUL","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN TEPOI","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SUNGAI KENYAH","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN PATI","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN TEBAKANG","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN SERIAN","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN SAMARAHAN ESTATE","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN TANAH PUTEH","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN LUBOK ANTU REBAN","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN PANGKALAN SORAH","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN SAINT JAMES RAYANG","negeri":"SARAWAK","daerah":"SERIAN"},
"‏Q14012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN SAINT EDWARD BELIMBING","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN SIBURAN BATU","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN BEDUP","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN SAINT PATRICK TANGGA","negeri":"SARAWAK","daerah":"SERIAN"},
"Q14016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN BALAI RINGIN","negeri":"SARAWAK","daerah":"SERIAN"},
"SIMPANAN-SERIAN": {"rujukan":"17","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SERIAN"},
"Q03001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN (A) MIS SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN ABANG AING SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03004": {"rujukan":"4","nama":"SJK CHUNG HUA SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN TEMUDOK KEM","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KEM PAKIT","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BAKONG SRI AMAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN GRAN/STUMBIN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN TANJUNG BIJAT","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN LELA PAHLAWAN","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN PULAU SEDUKU","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN MELUGU","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN ENGKILILI NO. 1","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q03014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN ST LUKE","negeri":"SARAWAK","daerah":"SRI AMAN"},
"SIMPANAN-SRI-AMAN": {"rujukan":"15","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SRI AMAN"},
"Q04001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN DATUK BANDAR DEBAK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN SEREMBANG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04003": {"rujukan":"3","nama":"SJK ( C ) CHUNG HUA PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN MANGUT SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN TAMBAK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN SEMARANG PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN ST PAUL ROBAN","negeri":"SARAWAK","daerah":"BETONG"},
"Q04008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN ABANG MOH SESSANG.","negeri":"SARAWAK","daerah":"BETONG"},
"Q04009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN HJ JUNID GERIGAT","negeri":"SARAWAK","daerah":"BETONG"},
"Q04010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN ABANG LEMAN KABONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04011": {"rujukan":"11","nama":"SJK CHUNG HUA KABONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN BALINGAN","negeri":"SARAWAK","daerah":"BETONG"},
"Q04013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAMPUNG BUDA SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN DIT DEBAK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KALOK, PUSA, BETONG.","negeri":"SARAWAK","daerah":"BETONG"},
"Q04017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SUPA PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN MALUDAM","negeri":"SARAWAK","daerah":"BETONG"},
"Q04019": {"rujukan":"19","nama":"SJKC CHUNG HUA MELUDAM","negeri":"SARAWAK","daerah":"BETONG"},
"Q04020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN KAMPUNG ALIT KABONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN PERPAT KABONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN SEBEMBAN","negeri":"SARAWAK","daerah":"BETONG"},
"Q04023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN BUNGIN SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04024": {"rujukan":"24","nama":"SJK CHUNG HUA DEBAK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN TUI","negeri":"SARAWAK","daerah":"BETONG"},
"Q04026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN SPINANG PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN BELADIN PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN TO' EMAN NYABOR","negeri":"SARAWAK","daerah":"BETONG"},
"Q04030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN KAMPUNG EMPELAM","negeri":"SARAWAK","daerah":"BETONG"},
"Q04031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN BATANG MARO","negeri":"SARAWAK","daerah":"BETONG"},
"Q04032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN ABANG ABDUL KADIR BETONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN TANJUNG ASSAM, SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04034": {"rujukan":"34","nama":"SJK (C) CHUNG HUA SPAOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN SERABANG PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN MEDANG PUSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN ABANG ABDUL RAHMAN","negeri":"SARAWAK","daerah":"BETONG"},
"Q04038": {"rujukan":"38","nama":"SJK (C) MIN SYN SARATOK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN KAMPUNG KUPANG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN HJ BOLLAH KABA SARATOK","negeri":"SARAWAK","daerah":"BETONG"},
"Q04041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN KAMPUNG PALOH","negeri":"SARAWAK","daerah":"BETONG"},
"Q04042": {"rujukan":"42","nama":"SJK (C) CHUNG HUA BETONG","negeri":"SARAWAK","daerah":"BETONG"},
"Q04043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN NANGA PASSA","negeri":"SARAWAK","daerah":"BETONG"},
"Q04044": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN KALAKA CENTRAL SARATOK","negeri":"SARAWAK","daerah":"BETONG"},
"SIMPANAN-BETONG": {"rujukan":"45","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"BETONG"},
"Q05001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN SARIKEI","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN (A) MIS SARIKEI","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN ABG HAJI MATAHIR","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN METHODIST","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN ST ANNE","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05006": {"rujukan":"6","nama":"SJK C KWANG CHIEN","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN MANDOR ARIS","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN ABANG AMIN","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN BANDAR BINTANGOR","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN GEMUAN","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN BUKIT KINYAU,SARIKEI","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN BUKIT NIBONG","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN NANGA STRAS","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN TANJUNG BUNDUNG","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN BUKIT PAPIT,BINTANGOR","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q05017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN ST. AUGUSTINE(M) MERADONG","negeri":"SARAWAK","daerah":"SARIKEI"},
"SIMPANAN-SARIKEI": {"rujukan":"18","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SARIKEI"},
"Q06001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ABANG ALI","negeri":"SARAWAK","daerah":"SIBU"},
"Q06002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BANDARAN NO.3","negeri":"SARAWAK","daerah":"SIBU"},
"Q06003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KAMPUNG BAHAGIA JAYA","negeri":"SARAWAK","daerah":"SIBU"},
"Q06004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN ULU SG MERAH","negeri":"SARAWAK","daerah":"SIBU"},
"Q06005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN BATU 10","negeri":"SARAWAK","daerah":"SIBU"},
"Q06006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN SEDC","negeri":"SARAWAK","daerah":"SIBU"},
"Q06007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BAWANG ASSAN","negeri":"SARAWAK","daerah":"SIBU"},
"Q06008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN SENTOSA","negeri":"SARAWAK","daerah":"SIBU"},
"Q06009": {"rujukan":"9","nama":"SJK METHODIST (M)","negeri":"SARAWAK","daerah":"SIBU"},
"Q06010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN (A) MIS SIBU","negeri":"SARAWAK","daerah":"SIBU"},
"Q06011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN SIBU JAYA,SIBU","negeri":"SARAWAK","daerah":"SIBU"},
"Q06012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN JLN DESHON","negeri":"SARAWAK","daerah":"SIBU"},
"Q06013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN BATU 15","negeri":"SARAWAK","daerah":"SIBU"},
"Q06014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN ST FRANCIS XAVIER","negeri":"SARAWAK","daerah":"SIBU"},
"Q06016": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN HUA HIN ENGLISH","negeri":"SARAWAK","daerah":"SIBU"},
"Q06017": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN ST RITA","negeri":"SARAWAK","daerah":"SIBU"},
"Q06019": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SACRED HEART (ENGLISH)","negeri":"SARAWAK","daerah":"SIBU"},
"Q06020": {"rujukan":"18","nama":"SJK ( C )THIAN HUA","negeri":"SARAWAK","daerah":"SIBU"},
"Q06021": {"rujukan":"19","nama":"SJK (C) CHUNG HUA","negeri":"SARAWAK","daerah":"SIBU"},
"Q06022": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN RANTAU PANJANG, SIBU","negeri":"SARAWAK","daerah":"SIBU"},
"Q06024": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN SAINT MARY","negeri":"SARAWAK","daerah":"SIBU"},
"SIMPANAN-SIBU": {"rujukan":"22","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"SIBU"},
"Q09001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN KAPIT","negeri":"SARAWAK","daerah":"KAPIT"},
"Q09004": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN CARDINAL VAUGHAN SONG","negeri":"SARAWAK","daerah":"KAPIT"},
"Q09005": {"rujukan":"3","nama":"SJK C HOCK LAM","negeri":"SARAWAK","daerah":"KAPIT"},
"Q09006": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN KAMPUNG BARU KAPIT","negeri":"SARAWAK","daerah":"KAPIT"},
"SIMPANAN-KAPIT": {"rujukan":"5","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"KAPIT"},
"Q09003": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN LONG BUSANG BELAGA.","negeri":"SARAWAK","daerah":"LONG BUSANG"},
"SIMPANAN-LONG-BUSANG": {"rujukan":"2","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"LONG BUSANG"},
"Q07001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN DATUK AWANG UDIN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN SAINT PATRICK","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KAMPUNG PETANAK","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN KAMPUNG SEBERANG, MUKAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN MUKAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN DUA SUNGAI","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN KAMPUNG TELLIAN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN PENAKUP ULU","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN KAMPUNG TEH, MUKAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN SUNGAI BADENGAN, MUKAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN SUNGAI PENIPAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN DATU PENGIRAN MOHD","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KAMPUNG SENAU","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAMPUNG BAKONG/TERUS","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KAMPUNG TANAM","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN SUNGAI UD","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SAINT BERNARD","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SAINT JOHN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN SAINT KEVIN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN KAMPUNG IGAN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN KAMPUNG TEH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN KPG BALAN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN SUNGAI KUT TENGAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN (A) MIS MUKAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN PARISH BALINGIAN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN KUALA BALINGIAN","negeri":"SARAWAK","daerah":"MUKAH"},
"Q07027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN KAMPUNG JEBUNGAN","negeri":"SARAWAK","daerah":"MUKAH"},
"SIMPANAN-MUKAH": {"rujukan":"28","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"MUKAH"},
"Q08001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ORG KAYA MUDA PAKERI,PALOH","negeri":"SARAWAK","daerah":"DARO"},
"Q08002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN ULU DARO, DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KAMPUNG NANGAR,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN CAMPORAN, DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN KAMPUNG BETANAK,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KAMPUNG TEBAANG , DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN KAMPUNG PENIBONG,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN PENIPAH,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN MOHD REDEH SAAI,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN ABG BUYUK JERIJEH","negeri":"SARAWAK","daerah":"DARO"},
"Q08011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPUNG PENASU,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN KAMPUNG PANGTRAY,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN ABANG GALAU RAJANG","negeri":"SARAWAK","daerah":"DARO"},
"Q08014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KAMPUNG SEMOP, DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KAMPUNG SABENA, DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KAMPUNG SERDENG DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KAMPUNG BRUIT , DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN ABG GESA,BELAWAI","negeri":"SARAWAK","daerah":"DARO"},
"Q08019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN KAMPUNG SALAH KECHIL,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN KAMPUNG PERGAU , MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN KAMPUNG SOK, MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN BAWANG TIAN, MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN KAMPUNG KUALA MATU , MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN ORG KAYA SERGUNIM,MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN ORG KAYA SELAIR,MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN HIJRAH BADONG,DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN KAMPUNG SEKAAN KECHIL, MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAAN TANJUNG MANIS","negeri":"SARAWAK","daerah":"DARO"},
"Q08029": {"rujukan":"29","nama":"SJK CHUNG HUA,MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN BRUAN MAPAL , MATU","negeri":"SARAWAK","daerah":"DARO"},
"Q08031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN KAMPUNG SEBAKO","negeri":"SARAWAK","daerah":"DARO"},
"Q08032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN KAMPUNG TEKAJONG , DARO","negeri":"SARAWAK","daerah":"DARO"},
"Q08034": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN KAMPUNG KUT, DARO","negeri":"SARAWAK","daerah":"DARO"},
"SIMPANAN-DARO": {"rujukan":"34","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"DARO"},
"Q10001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN BINTULU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN KIDURONG 1, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KIDURONG 2, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN KAMPUNG BARU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN TANJUNG BATU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KUALA TATAU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN ORANG KAYA MOHAMMAD, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN (A) MIS BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN ST ANTHONY, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN TATAU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPUNG JEPAK, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN ASYAKIRIN, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KUALA NYALAU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN DESA LAVANG, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KAMPUNG NYALAU, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10016": {"rujukan":"16","nama":"SJK CHUNG HUA 2, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN SUNGAI TISANG, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SEBAUH","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN SUNGAI SENGIAN, SEBAUH","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN BUKIT BALAI","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN LABANG, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN PANDAN, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10023": {"rujukan":"23","nama":"SJK CHUNG HUA, BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"Q10024": {"rujukan":"24","nama":"SEKOLAH RENDAH ISLAM TAHFIZ DARUL HANA' BINTULU","negeri":"SARAWAK","daerah":"BINTULU"},
"SIMPANAN-BINTULU": {"rujukan":"25","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"BINTULU"},
"Q09002": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ABUN MATU BELAGA","negeri":"SARAWAK","daerah":"ABUN MATU"},
"SIMPANAN-ABUN-MATU": {"rujukan":"2","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"ABUN MATU"},
"Q11001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN BELURU CENTRAL BAKONG","negeri":"SARAWAK","daerah":"MIRI"},
"Q11002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN DATO SHARIF HAMID MARUDI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN GOOD SHEPHERD MARUDI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN JALAN BINTANG MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN KAMPUNG ANGUS, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KAMPUNG BERAYA MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN KAMPUNG BULAU","negeri":"SARAWAK","daerah":"MIRI"},
"Q11008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN KAMPUNG BUNGAI, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN KELAPA SAWIT NO. 2","negeri":"SARAWAK","daerah":"MIRI"},
"Q11010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN KAMPUNG LUAK, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPUNG SELANYAU, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN BENAWA BARAM","negeri":"SARAWAK","daerah":"MIRI"},
"Q11013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KELAPA SAWIT NO. 1","negeri":"SARAWAK","daerah":"MIRI"},
"Q11014": {"rujukan":"14","nama":"SEK KEB KELAPA SAWIT NO.3","negeri":"SARAWAK","daerah":"MIRI"},
"Q11015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KELAPA SAWIT NO. 4","negeri":"SARAWAK","daerah":"MIRI"},
"Q11016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KELAPA SAWIT NO.5","negeri":"SARAWAK","daerah":"MIRI"},
"Q11017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KELURU TENGAH, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN SENADIN","negeri":"SARAWAK","daerah":"MIRI"},
"Q11019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN KAMPUNG BAKAM, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN KAMPUNG KUALA SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN KAMPUNG MASJID, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN KUALA BARAM II, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN LAMBIR VILLAGE, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN LUTONG, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN PUJUT CORNER, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN TEMENGGONG DATUK MUIP MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11028": {"rujukan":"28","nama":"SJK (C) NORTH MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11029": {"rujukan":"29","nama":"SR SRI MAWAR, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11030": {"rujukan":"30","nama":"SJK (C) CHUNG HUA KROKOP, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11031": {"rujukan":"31","nama":"SJK (C) CHUNG HUA TUDAN, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11032": {"rujukan":"32","nama":"SJK (C) CHEE MUNG, NIAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q11033": {"rujukan":"33","nama":"SJK (C) CHUNG HUA BAKAM, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11035": {"rujukan":"34","nama":"SJK (C) CHUNG SAN RIAM, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11036": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN SOUTH, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11037": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN TUDAN, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11038": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN ANCHI MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11039": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN BELIAU AHAD, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11040": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN KAMPUNG TARIKAN, NIAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q11041": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN KAMPUNG SUBAK, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11042": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN KUALA BARAM, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11043": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN MERBAU MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11044": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN RIAM BATU DUA MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11045": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN KITA NIAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q11046": {"rujukan":"45","nama":"SEKOLAH KEBANGSAAN ST COLUMBA, MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11047": {"rujukan":"46","nama":"SEKOLAH KEBANGSAAN ST JOSEPH MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11048": {"rujukan":"47","nama":"SEKOLAH KEBANGSAAN SAYED OTHMAN MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11049": {"rujukan":"48","nama":"SEKOLAH KEBANGSAAN (A) MIS MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11050": {"rujukan":"49","nama":"SEKOLAH KEBANGSAAN BATU NIAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q11051": {"rujukan":"50","nama":"SEKOLAH KEBANGSAAN BATU TELLINGAI, SUAI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11052": {"rujukan":"51","nama":"SEKOLAH KEBANGSAAN BEKENU, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11053": {"rujukan":"52","nama":"SEKOLAH KEBANGSAAN PULAU MELAYU MIRI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11054": {"rujukan":"53","nama":"SEKOLAH KEBANGSAAN TANJUNG BELIPAT, NIAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q11055": {"rujukan":"54","nama":"SEKOLAH KEBANGSAAN TAWAKAL SATAP, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11056": {"rujukan":"55","nama":"SEKOLAH KEBANGSAAN KAMPUNG IRAN, SUAI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11057": {"rujukan":"56","nama":"SEKOLAH KEBANGSAAN BELIAU ISA, SIBUTI","negeri":"SARAWAK","daerah":"MIRI"},
"Q11058": {"rujukan":"57","nama":"MADRASAH ASSYIBYAN","negeri":"SARAWAK","daerah":"MIRI"},
"Q11059": {"rujukan":"58","nama":"SEKOLAH KEBANGSAAN SG MANONG","negeri":"SARAWAK","daerah":"MIRI"},
"Q11060": {"rujukan":"59","nama":"SEKOLAH RENDAH ISLAM INTEGRASI TAHFIZ","negeri":"SARAWAK","daerah":"MIRI"},
"Q11061": {"rujukan":"60","nama":"SEKOLAH KEBANGSAAN LAMAUS","negeri":"SARAWAK","daerah":"MIRI"},
"SIMPANAN-MIRI": {"rujukan":"61","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"MIRI"},
"Q13001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN MELAYU PUSAT","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BANDAR LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN GADONG LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN LIMPAKI","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KAMPUNG PAHLAWAN","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN ST EDMUND","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN SUNGAI POYAN","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN TELAHAK","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN BATU EMPAT, LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN LIMPAKU PINANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN TEDUNGAN LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN TIGA KAMPONG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13014": {"rujukan":"14","nama":"SJK CHUNG HWA","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KUBONG, LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN MERITAM LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN BUKIT LUBA","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN LUBOK TEKUROK","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13020": {"rujukan":"20","nama":"SEKOLAH KEBANGSAAN MENUANG LIMBANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN BATU DANAU","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q13022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN KUALA AWANG","negeri":"SARAWAK","daerah":"LIMBANG"},
"SIMPANAN-LIMBANG": {"rujukan":"23","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"LIMBANG"},
"Q12001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ULU MERAPOK,","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN MERAPOK LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN KERANGAN, LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN LADANG BARU,","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN KPG. SEBERANG, KUALA LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN KUALA LAWAS, LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN BELIPAT","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN PUNANG, LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN PUSAT","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN (A) MIS LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN BATU 5, LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN TRUSAN, LAWAS","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN SUNDAR,","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN AWAT-AWAT, SUNDAR","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN LUAGAN, SUNDAR","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN ARU BARU, SUNDAR","negeri":"SARAWAK","daerah":"LAWAS"},
"Q12017": {"rujukan":"17","nama":"SJK SOON HWA","negeri":"SARAWAK","daerah":"LAWAS"},
"SIMPANAN-LAWAS": {"rujukan":"18","nama":"SIMPANAN DAERAH","negeri":"SARAWAK","daerah":"LAWAS"},


});
