Object.assign(window.SCHOOLS, {
  "K04001": {"rujukan":"1","nama":"SEKOLAH KEBANGSAAN ASAM JAWA","negeri":"KEDAH","daerah":"BALING"},
"K04002": {"rujukan":"2","nama":"SEKOLAH KEBANGSAAN BADANG","negeri":"KEDAH","daerah":"BALING"},
"K04003": {"rujukan":"3","nama":"SEKOLAH KEBANGSAAN BALING","negeri":"KEDAH","daerah":"BALING"},
"K04004": {"rujukan":"4","nama":"SEKOLAH KEBANGSAAN BATU PEKAKA","negeri":"KEDAH","daerah":"BALING"},
"K04005": {"rujukan":"5","nama":"SEKOLAH KEBANGSAAN BINJUL DALAM","negeri":"KEDAH","daerah":"BALING"},
"K04006": {"rujukan":"6","nama":"SEKOLAH KEBANGSAAN BINJUL LUAR","negeri":"KEDAH","daerah":"BALING"},
"K04007": {"rujukan":"7","nama":"SEKOLAH KEBANGSAAN DALAM WANG","negeri":"KEDAH","daerah":"BALING"},
"K04008": {"rujukan":"8","nama":"SEKOLAH KEBANGSAAN IBOI","negeri":"KEDAH","daerah":"BALING"},
"K04009": {"rujukan":"9","nama":"SEKOLAH KEBANGSAAN KAMPONG BANDAR","negeri":"KEDAH","daerah":"BALING"},
"K04010": {"rujukan":"10","nama":"SEKOLAH KEBANGSAAN SERA","negeri":"KEDAH","daerah":"BALING"},
"K04011": {"rujukan":"11","nama":"SEKOLAH KEBANGSAAN KAMPONG PADANG","negeri":"KEDAH","daerah":"BALING"},
"K04012": {"rujukan":"12","nama":"SEKOLAH KEBANGSAAN KAMPONG KEDA","negeri":"KEDAH","daerah":"BALING"},
"K04013": {"rujukan":"13","nama":"SEKOLAH KEBANGSAAN KUALA KETIL","negeri":"KEDAH","daerah":"BALING"},
"K04014": {"rujukan":"14","nama":"SEKOLAH KEBANGSAAN KUALA KUANG","negeri":"KEDAH","daerah":"BALING"},
"K04015": {"rujukan":"15","nama":"SEKOLAH KEBANGSAAN KUALA MERAH","negeri":"KEDAH","daerah":"BALING"},
"K04016": {"rujukan":"16","nama":"SEKOLAH KEBANGSAAN KUALA PEGANG","negeri":"KEDAH","daerah":"BALING"},
"K04017": {"rujukan":"17","nama":"SEKOLAH KEBANGSAAN KUALA SAMAK","negeri":"KEDAH","daerah":"BALING"},
"K04018": {"rujukan":"18","nama":"SEKOLAH KEBANGSAAN LANAI","negeri":"KEDAH","daerah":"BALING"},
"K04019": {"rujukan":"19","nama":"SEKOLAH KEBANGSAAN MALAU","negeri":"KEDAH","daerah":"BALING"},
"K04020": {"rujukan":"20","nama":"SEKOLAH KHAS BALING","negeri":"KEDAH","daerah":"BALING"},
"K04021": {"rujukan":"21","nama":"SEKOLAH KEBANGSAAN MOHD ARIFF ABDULLAH","negeri":"KEDAH","daerah":"BALING"},
"K04022": {"rujukan":"22","nama":"SEKOLAH KEBANGSAAN PAYA BESAR","negeri":"KEDAH","daerah":"BALING"},
"K04023": {"rujukan":"23","nama":"SEKOLAH KEBANGSAAN PENGHULU ABU BAKAR","negeri":"KEDAH","daerah":"BALING"},
"K04024": {"rujukan":"24","nama":"SEKOLAH KEBANGSAAN PULAI","negeri":"KEDAH","daerah":"BALING"},
"K04025": {"rujukan":"25","nama":"SEKOLAH KEBANGSAAN RAMBONG PULAI","negeri":"KEDAH","daerah":"BALING"},
"K04026": {"rujukan":"26","nama":"SEKOLAH KEBANGSAAN SEBERANG KETIL","negeri":"KEDAH","daerah":"BALING"},
"K04027": {"rujukan":"27","nama":"SEKOLAH KEBANGSAAN SELARONG","negeri":"KEDAH","daerah":"BALING"},
"K04028": {"rujukan":"28","nama":"SEKOLAH KEBANGSAN SERI BAYU","negeri":"KEDAH","daerah":"BALING"},
"K04029": {"rujukan":"29","nama":"SEKOLAH KEBANGSAAN SERI INAS BAKAI","negeri":"KEDAH","daerah":"BALING"},
"K04030": {"rujukan":"30","nama":"SEKOLAH KEBANGSAAN SERI JEMERLI","negeri":"KEDAH","daerah":"BALING"},
"K04031": {"rujukan":"31","nama":"SEKOLAH KEBANGSAAN SIONG","negeri":"KEDAH","daerah":"BALING"},
"K04032": {"rujukan":"32","nama":"SEKOLAH KEBANGSAAN SYED SHEH","negeri":"KEDAH","daerah":"BALING"},
"K04033": {"rujukan":"33","nama":"SEKOLAH KEBANGSAAN TANJUNG PARI","negeri":"KEDAH","daerah":"BALING"},
"K04034": {"rujukan":"34","nama":"SEKOLAH KEBANGSAAN TAWAR","negeri":"KEDAH","daerah":"BALING"},
"K04035": {"rujukan":"35","nama":"SEKOLAH KEBANGSAAN TIAK","negeri":"KEDAH","daerah":"BALING"},
"K04036": {"rujukan":"36","nama":"SEKOLAH KEBANGSAAN TITI GANTUNG","negeri":"KEDAH","daerah":"BALING"},
"K04037": {"rujukan":"37","nama":"SEKOLAH KEBANGSAAN TELOI KANAN","negeri":"KEDAH","daerah":"BALING"},
"K04038": {"rujukan":"38","nama":"SEKOLAH KEBANGSAAN TELOK TEDURI","negeri":"KEDAH","daerah":"BALING"},
"K04039": {"rujukan":"39","nama":"SEKOLAH KEBANGSAAN TEMBAK","negeri":"KEDAH","daerah":"BALING"},
"K04040": {"rujukan":"40","nama":"SEKOLAH KEBANGSAAN TUNKU PUAN HABSAH","negeri":"KEDAH","daerah":"BALING"},
"K04041": {"rujukan":"41","nama":"SEKOLAH KEBANGSAAN TUNKU PUTERA","negeri":"KEDAH","daerah":"BALING"},
"K04042": {"rujukan":"42","nama":"SEKOLAH KEBANGSAAN ULU BAKAI","negeri":"KEDAH","daerah":"BALING"},
"K04043": {"rujukan":"43","nama":"SEKOLAH KEBANGSAAN ULU TAWAR","negeri":"KEDAH","daerah":"BALING"},
"K04044": {"rujukan":"44","nama":"SEKOLAH KEBANGSAAN KAMPONG SADEK","negeri":"KEDAH","daerah":"BALING"},
"K04045": {"rujukan":"45","nama":"SEKOLAH KEBANGSAAN KUALA KUPANG","negeri":"KEDAH","daerah":"BALING"},
"K04046": {"rujukan":"46","nama":"KAFA SEKOLAH RENDAH ISLAM DARUL HIJRAH","negeri":"KEDAH","daerah":"BALING"},
"K04047": {"rujukan":"47","nama":"MADRASAH ISLAHIAH DINIAH","negeri":"KEDAH","daerah":"BALING"},
"K04048": {"rujukan":"48","nama":"SRITI DARUL ULUM","negeri":"KEDAH","daerah":"BALING"},
"K04049": {"rujukan":"49","nama":"SMA DINIAH ISLAMIAH","negeri":"KEDAH","daerah":"BALING"},
"K04049": {"rujukan":"50","nama":"SRA DINIAH ISLAMIAH","negeri":"KEDAH","daerah":"BALING"},
"K04050": {"rujukan":"51","nama":"SEKOLAH RENDAH TAHFIZ SAINS AL FALAH","negeri":"KEDAH","daerah":"BALING"},
"K04051": {"rujukan":"52","nama":"MAAHAD TAFAQQUH FIDDIN AN-NUR","negeri":"KEDAH","daerah":"BALING"},
"K04052": {"rujukan":"53","nama":"SEKOLAH RENDAH ISLAM RAUDHATUL MUSLIMIN","negeri":"KEDAH","daerah":"BALING"},
"SIMPANAN-BALING": {"rujukan":"54","nama":"SIMPANAN DAERAH","negeri":"KEDAH","daerah":"BALING"},


  });            
