window.SCHOOLS = {
"WPKL001": {"rujukan":"1","nama":"KAFA SURAU KG. BELUKUT","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL002": {"rujukan":"2","nama":"KAFA SURAU PERUMAHAN LDA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL003": {"rujukan":"3","nama":"KAFA BAITUL HIDAYAH, FLAT JKR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL004": {"rujukan":"4","nama":"KAFA AL-ROSHIDAH KG. KIAMSAM WAWASAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL005": {"rujukan":"5","nama":"KAFA MASJID SIRAJUL ISLAM, TANJUNG ARU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL006": {"rujukan":"6","nama":"KAFA ADZ-DZIKRULLAH KG RANCHA-RANCHA LAUT.","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL007": {"rujukan":"7","nama":"KAFA SURAU KG. BATU MANIKAR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL008": {"rujukan":"8","nama":"KAFA AL-EHSANIAH KG. MUSLIM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL009": {"rujukan":"9","nama":"KAFA QURRATUL 'AIN KAMPUNG LAJAU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL010": {"rujukan":"10","nama":"KAFA NUR IMAN MASJID NUR IMAN, KG. GANGGARAK","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL011": {"rujukan":"11","nama":"KAFA AL-HIDAYAH KG. KIAMSAM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL012": {"rujukan":"12","nama":"KAFA SURAU AR-RAUDHAH, KG. BUKIT KUDA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL013": {"rujukan":"13","nama":"KAFA NUR HIKMAH SURAU KG. KILAN KASSIM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL014": {"rujukan":"14","nama":"KAFA SURAU AL-IRSYAD, KG. KILAN PULAU AKAR","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL015": {"rujukan":"15","nama":"KAFA SURAU UWAIS ALQARNI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL016": {"rujukan":"16","nama":"KAFA AL-HIDAYAH MASJID AL-MUNAWWAR KG. POHON BATU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL017": {"rujukan":"17","nama":"KAFA DARUL FURQOON BALAI RAYA KG. GERSIK","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL018": {"rujukan":"18","nama":"KAFA JANNATUL AN-NAIM, MASJID AL-MUTTAKIN IOFC KERUPANG","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKL019": {"rujukan":"19","nama":"KAFA AS-SHOBIRIN KG.BARU PULAU DA'AT","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKS031": {"rujukan":"20","nama":"SEKOLAH RENDAH INTEGRASI TERAS ISLAM (SRITI) LABUAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPKS038": {"rujukan":"21","nama":"MADRASAH AL HAQ WP LABUAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL001": {"rujukan":"22","nama":"SRA ATTARBIAH AL ISLAMIAH PEKAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL002": {"rujukan":"23","nama":"SRA DARUL ULUM MEMBEDAI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL003": {"rujukan":"24","nama":"SRA AL-AHMADIAH PATAU-PATAU","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL004": {"rujukan":"25","nama":"SRA NURUTTAQWA RANCHA-RANCHA","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL005": {"rujukan":"26","nama":"SRA AL- LAMUDIN KG SG BEDAUN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL006": {"rujukan":"27","nama":"SRA ABU BAKAR BEBULOH","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL007": {"rujukan":"28","nama":"SRA AT-TAUFIQIAH SUNGAI MIRI","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL008": {"rujukan":"29","nama":"SRA NURUL HIDAYAH LAYANG-LAYANGAN","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL009": {"rujukan":"30","nama":"SRA NURUL FALAH BUKIT KALAM","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"WPL010": {"rujukan":"31","nama":"SEKOLAH INTEGRASI RENDAH AGAMA JAWI (SIRAJ) SAIDINA UMAR AL-KHATTAB","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},
"SIMPANAN-LABUAN": {"rujukan":"32","nama":"SIMPANAN DAERAH","negeri":"WILAYAH PERSEKUTUAN","daerah":"ZON LABUAN"},

  "DBA0001": {"rujukan":"1","nama":"SEK KEB ALOR BAKAT","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0002": {"rujukan":"2","nama":"SEK KEB BACHOK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0003": {"rujukan":"3","nama":"SEK KEB BADAK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0004": {"rujukan":"4","nama":"SEK KEB BAKONG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0005": {"rujukan":"5","nama":"SEK KEB BEKELAM","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0006": {"rujukan":"6","nama":"SEK KEB SRI KEMUNTING","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA007": {"rujukan":"7","nama":"SEK KEB BERIS KUBOR BESAR","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0008": {"rujukan":"8","nama":"SEK KEB BERIS PANCHOR","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0009": {"rujukan":"9","nama":"SEK KEB BUKIT MARAK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0010": {"rujukan":"10","nama":"SEK KEB CHANTUM","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0011": {"rujukan":"11","nama":"SEK KEB GUNONG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0012": {"rujukan":"12","nama":"SEK KEB JELAWAT","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0013": {"rujukan":"13","nama":"SEK KEB KAMPUNG CHAP","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0014": {"rujukan":"14","nama":"SEK KEB KANDIS","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0015": {"rujukan":"15","nama":"SEK KEB KETING","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0016": {"rujukan":"16","nama":"SEK KEB KOLAM","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0017": {"rujukan":"17","nama":"SEK KEB KUBANG GOLOK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0018": {"rujukan":"18","nama":"SEK KEB KUBANG TELAGA","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0019": {"rujukan":"19","nama":"SEK KEB KUCHELONG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0020": {"rujukan":"20","nama":"SEK KEB PAK BADOL","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0021": {"rujukan":"21","nama":"SEK KEB PA' PURA","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0022": {"rujukan":"22","nama":"SEK KEB PANTAI SENAK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0023": {"rujukan":"23","nama":"SEK KEB PAUH SEMBILAN","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0024": {"rujukan":"24","nama":"SEK KEB PENGKALAN CHENGAL","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0025": {"rujukan":"25","nama":"SEK KEB PERUPOK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0026": {"rujukan":"26","nama":"SEK KEB SENENG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0027": {"rujukan":"27","nama":"SEK KEB SUNGAI DUA","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0028": {"rujukan":"28","nama":"SEK KEB TANJONG JENERA","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0029": {"rujukan":"29","nama":"SEK KEB TAWANG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0030": {"rujukan":"30","nama":"SEK KEB TELAGA ARA","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0031": {"rujukan":"31","nama":"SEK KEB BERIS LALANG","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0032": {"rujukan":"32","nama":"SEK KEB TANGOK","negeri":"KELANTAN","daerah":"BACHOK"},
"DBA0033": {"rujukan":"33","nama":"SEK KEB JELAWAT 2","negeri":"KELANTAN","daerah":"BACHOK"},
"DBB0031": {"rujukan":"34","nama":"SEK KEB SERI KEMUDI","negeri":"KELANTAN","daerah":"BACHOK"},
"SIMPANAN-BACHOK": {"rujukan":"35","nama":"SIMPANAN DAERAH","negeri":"KELANTAN","daerah":"BACHOK"},
  "DBA8001": {"rujukan":"1","nama":"SK BERTAM","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8002": {"rujukan":"2","nama":"SK GUA MUSANG","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8003": {"rujukan":"3","nama":"SK JERAM TEKOH","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8004": {"rujukan":"4","nama":"SK LIMAU KASTURI","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8005": {"rujukan":"5","nama":"SK PALOH 1 & 2","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8006": {"rujukan":"6","nama":"SK RENOK BARU","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8007": {"rujukan":"7","nama":"SK STAR","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8008": {"rujukan":"8","nama":"SK SUNGAI TERAH","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8009": {"rujukan":"9","nama":"SK CHALIL","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8010": {"rujukan":"10","nama":"SK JEREK","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8011": {"rujukan":"11","nama":"SK LEBIR","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8012": {"rujukan":"12","nama":"SK PALOH 3","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8013": {"rujukan":"13","nama":"SK PASIR TUMBOH","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8014": {"rujukan":"14","nama":"SK SRI CHIKU 1","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8016": {"rujukan":"15","nama":"SK PERASU","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8017": {"rujukan":"16","nama":"SK CHIKU 3","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8018": {"rujukan":"17","nama":"SK ARING","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8019": {"rujukan":"18","nama":"SK KUALA SUNGAI","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8020": {"rujukan":"19","nama":"SK CHIKU 7","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8021": {"rujukan":"20","nama":"SK LIMAU KASTURI 2","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8022": {"rujukan":"21","nama":"SK SRI WANGI","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8023": {"rujukan":"22","nama":"SK SRI CHIKU 2","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8024": {"rujukan":"23","nama":"SK TENGKU MUHAMMAD FAKHRY PETRA","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8025": {"rujukan":"24","nama":"SK BALAR","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8034": {"rujukan":"25","nama":"SK MERANTO","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8035": {"rujukan":"26","nama":"SK LEPAN JAYA","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA8036": {"rujukan":"27","nama":"SK SRI WANGI 2","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBAA001": {"rujukan":"28","nama":"SK KUALA BETIS","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBC8001": {"rujukan":"29","nama":"SJK C GUA MUSANG","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA7411": {"rujukan":"30","nama":"SK PASIR LINGGI","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"SIMPANAN-GUA-MUSANG": {"rujukan":"31","nama":"SIMPANAN DAERAH","negeri":"KELANTAN","daerah":"GUA MUSANG"},
"DBA9001": {"rujukan":"1","nama":"SK AYER LANAS","negeri":"KELANTAN","daerah":"JELI"},
"DBA9002": {"rujukan":"2","nama":"SK BATU MELINTANG","negeri":"KELANTAN","daerah":"JELI"},
"DBA9003": {"rujukan":"3","nama":"SK BUKIT JERING","negeri":"KELANTAN","daerah":"JELI"},
"DBA9004": {"rujukan":"4","nama":"SK GEMANG","negeri":"KELANTAN","daerah":"JELI"},
"DBA9005": {"rujukan":"5","nama":"SK JELI 1","negeri":"KELANTAN","daerah":"JELI"},
"DBA9006": {"rujukan":"6","nama":"SK KALAI","negeri":"KELANTAN","daerah":"JELI"},
"DBA9007": {"rujukan":"7","nama":"SK KUALA BALAH","negeri":"KELANTAN","daerah":"JELI"},
"DBA9008": {"rujukan":"8","nama":"SK KUBOR DATU","negeri":"KELANTAN","daerah":"JELI"},
"DBA9009": {"rujukan":"9","nama":"SK LEGEH","negeri":"KELANTAN","daerah":"JELI"},
"DBA9010": {"rujukan":"10","nama":"SK LUBOK BONGOR","negeri":"KELANTAN","daerah":"JELI"},
"DBA9011": {"rujukan":"11","nama":"SK PENDOK","negeri":"KELANTAN","daerah":"JELI"},
"DBA9012": {"rujukan":"12","nama":"SK SUNGAI LONG","negeri":"KELANTAN","daerah":"JELI"},
"DBA9013": {"rujukan":"13","nama":"SK JELI 2","negeri":"KELANTAN","daerah":"JELI"},
"DBA9015": {"rujukan":"14","nama":"SK PASIR DUSUN","negeri":"KELANTAN","daerah":"JELI"},
"SIMPANAN-JELI": {"rujukan":"15","nama":"SIMPANAN DAERAH","negeri":"KELANTAN","daerah":"JELI"},

};
